/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";

export const TradeTraversalEntity: core.serialization.ObjectSchema<
    serializers.TradeTraversalEntity.Raw,
    SayariAnalyticsApi.TradeTraversalEntity
> = core.serialization.object({
    type: core.serialization.string(),
    label: core.serialization.string(),
    countries: core.serialization.list(core.serialization.string()),
    risks: core.serialization.list(core.serialization.string()),
});

export declare namespace TradeTraversalEntity {
    interface Raw {
        type: string;
        label: string;
        countries: string[];
        risks: string[];
    }
}
