/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Label in English if available. Translation performed by Sayari.
 */
export declare type EntityTranslatedLabel = string;
