/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * True if the entity has the "Sanctioned" risk factor, otherwise false. See https://docs.sayari.com/risk/#sanctioned
 */
export declare type EntitySanctioned = boolean;
