/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const PaginatedResponse: core.serialization.ObjectSchema<serializers.PaginatedResponse.Raw, SayariAnalyticsApi.PaginatedResponse>;
export declare namespace PaginatedResponse {
    interface Raw {
        limit: number;
        size: serializers.SizeInfo.Raw;
    }
}
