/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../..";

/**
 * OK
 *
 * @example
 *     {}
 */
export interface GetSourceResponse extends SayariAnalyticsApi.Source {}
