/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const SupplierOrBuyer: core.serialization.ObjectSchema<
    serializers.SupplierOrBuyer.Raw,
    SayariAnalyticsApi.SupplierOrBuyer
> = core.serialization
    .object({
        metadata: core.serialization.lazyObject(async () => (await import("../../..")).SupplierMetadata),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).EntityDetails));

export declare namespace SupplierOrBuyer {
    interface Raw extends serializers.EntityDetails.Raw {
        metadata: serializers.SupplierMetadata.Raw;
    }
}
