/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const BuyerSearchResults: core.serialization.ObjectSchema<serializers.BuyerSearchResults.Raw, SayariAnalyticsApi.BuyerSearchResults>;
export declare namespace BuyerSearchResults {
    interface Raw extends serializers.PaginatedResponse.Raw {
        offset: number;
        next: boolean;
        data: serializers.SupplierOrBuyerHits.Raw;
    }
}
