/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const VolumeAggregates: core.serialization.ObjectSchema<serializers.VolumeAggregates.Raw, SayariAnalyticsApi.VolumeAggregates>;
export declare namespace VolumeAggregates {
    interface Raw {
        key: string;
        doc_count: number;
        latest_shipment_date: serializers.LatestShipmentDate.Raw;
    }
}
