/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ClientName = "sayari-go" | "sayari-python" | "sayari-java" | "sayari-node";

export const ClientName = {
    Go: "sayari-go",
    Python: "sayari-python",
    Java: "sayari-java",
    Node: "sayari-node",
} as const;
