/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface ReferencedByData {
    record: Sayari.RecordDetails;
    type: Sayari.ReferencedByDataType;
}
