/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface RelationshipData {
    target: Sayari.EntityDetails;
    /** Additional information for each [relationship type](/sayari-library/ontology/relationships). */
    types: Record<Sayari.Relationships, Sayari.RelationshipInfo[] | undefined>;
    dates: string[];
    firstObserved?: string;
    former?: boolean;
    lastObserved?: string;
    startDate?: string;
    endDate?: string;
}
