/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const CreateProjectEntityAttributeRequest: core.serialization.ObjectSchema<
    serializers.CreateProjectEntityAttributeRequest.Raw,
    Sayari.CreateProjectEntityAttributeRequest
> = core.serialization.object({
    field: core.serialization.string(),
    value: core.serialization.string(),
    matchResolution: core.serialization.property("match_resolution", core.serialization.boolean()),
});

export declare namespace CreateProjectEntityAttributeRequest {
    export interface Raw {
        field: string;
        value: string;
        match_resolution: boolean;
    }
}
