/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { CreateProjectEntityAttributeResponseData } from "./CreateProjectEntityAttributeResponseData";

export const CreateProjectEntityAttributeResponse: core.serialization.ObjectSchema<
    serializers.CreateProjectEntityAttributeResponse.Raw,
    Sayari.CreateProjectEntityAttributeResponse
> = core.serialization.object({
    data: CreateProjectEntityAttributeResponseData,
});

export declare namespace CreateProjectEntityAttributeResponse {
    export interface Raw {
        data: CreateProjectEntityAttributeResponseData.Raw;
    }
}
