/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface ProjectEntityUpstream {
    risk: Sayari.Risk[];
    countries: Sayari.Country[];
    entities: number;
    matchHasUpstream: Record<string, boolean>;
    matchProducts: Record<string, string[]>;
}
