/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

export interface RoleMember {
    id: string;
    type: SayariAnalyticsApi.RoleMemberType;
    role: SayariAnalyticsApi.Role;
    created: string;
    updated: string;
}
