/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * @example
 *     {
 *         type: Sayari.ResourceType.Entity,
 *         project: "GNJbkG",
 *         entityId: "Zk0qOaM2SSYg_ZhsljykMQ",
 *         customFields: {
 *             "properties": {
 *                 "custom_name": "Victoria Beckham"
 *             }
 *         }
 *     }
 */
export interface SaveEntityRequest {
    type: Sayari.ResourceType;
    /** The project identifier. */
    project: string;
    /** The entity identifier. */
    entityId: string;
    /** <Warning>This property is in beta and is subject to change. It is provided for early access and testing purposes only.</Warning> custom user key/value pairs (key must be prefixed with "custom_" and value must be "string" type) */
    customFields?: unknown;
}
