/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const CreateProjectEntitySupplyChainSnapshotResponse: core.serialization.ObjectSchema<
    serializers.CreateProjectEntitySupplyChainSnapshotResponse.Raw,
    Sayari.CreateProjectEntitySupplyChainSnapshotResponse
> = core.serialization.object({
    snapshotId: core.serialization.property("snapshot_id", core.serialization.string()),
});

export declare namespace CreateProjectEntitySupplyChainSnapshotResponse {
    export interface Raw {
        snapshot_id: string;
    }
}
