/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const ProjectEntitySupplyChainSnapshotData: core.serialization.ObjectSchema<
    serializers.ProjectEntitySupplyChainSnapshotData.Raw,
    Sayari.ProjectEntitySupplyChainSnapshotData
> = core.serialization.object({
    snapshotId: core.serialization.property("snapshot_id", core.serialization.string()),
    label: core.serialization.string(),
    releaseTag: core.serialization.property("release_tag", core.serialization.string()),
    partialResults: core.serialization.property("partial_results", core.serialization.boolean()),
    exploredCount: core.serialization.property("explored_count", core.serialization.number()),
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    updatedAt: core.serialization.property("updated_at", core.serialization.string()),
});

export declare namespace ProjectEntitySupplyChainSnapshotData {
    export interface Raw {
        snapshot_id: string;
        label: string;
        release_tag: string;
        partial_results: boolean;
        explored_count: number;
        created_at: string;
        updated_at: string;
    }
}
