/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { ProjectEntitySupplyChainSnapshotDetailData } from "./ProjectEntitySupplyChainSnapshotDetailData";

export const ProjectEntitySupplyChainSnapshotByIdResponse: core.serialization.ObjectSchema<
    serializers.ProjectEntitySupplyChainSnapshotByIdResponse.Raw,
    Sayari.ProjectEntitySupplyChainSnapshotByIdResponse
> = core.serialization.object({
    data: ProjectEntitySupplyChainSnapshotDetailData,
});

export declare namespace ProjectEntitySupplyChainSnapshotByIdResponse {
    export interface Raw {
        data: ProjectEntitySupplyChainSnapshotDetailData.Raw;
    }
}
