/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const SupplyChainNode: core.serialization.ObjectSchema<serializers.SupplyChainNode.Raw, Sayari.SupplyChainNode> =
    core.serialization.object({
        id: core.serialization.string(),
        entityId: core.serialization.property("entity_id", core.serialization.string()),
        label: core.serialization.string(),
        type: core.serialization.string(),
        riskFactors: core.serialization.property("risk_factors", core.serialization.list(core.serialization.string())),
        countries: core.serialization.list(core.serialization.string()),
    });

export declare namespace SupplyChainNode {
    export interface Raw {
        id: string;
        entity_id: string;
        label: string;
        type: string;
        risk_factors: string[];
        countries: string[];
    }
}
