/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const TraversalRelationshipData: core.serialization.ObjectSchema<
    serializers.TraversalRelationshipData.Raw,
    SayariAnalyticsApi.TraversalRelationshipData
> = core.serialization.object({
    values: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).RelationshipInfo)
    ),
    former: core.serialization.boolean().optional(),
    startDate: core.serialization.property("start_date", core.serialization.string().optional()),
    lastObserved: core.serialization.property("last_observed", core.serialization.string().optional()),
    endDate: core.serialization.property("end_date", core.serialization.string().optional()),
});

export declare namespace TraversalRelationshipData {
    interface Raw {
        values: serializers.RelationshipInfo.Raw[];
        former?: boolean | null;
        start_date?: string | null;
        last_observed?: string | null;
        end_date?: string | null;
    }
}
