/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetUsage {
    /**
     * An ISO 8601 encoded date string indicating the starting time period to obtain usage stats. In the format YYYY-MM-DD
     */
    from?: string;
    /**
     * An ISO 8601 encoded date string indicating the ending time period to obtain usage stats. In the format YYYY-MM-DD
     */
    to?: string;
}
