/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { ScreenResponseAttributeValue } from "./ScreenResponseAttributeValue";

export const ScreenResponseAttribute: core.serialization.ObjectSchema<
    serializers.ScreenResponseAttribute.Raw,
    Sayari.ScreenResponseAttribute
> = core.serialization.object({
    matchResolution: core.serialization.property("match_resolution", core.serialization.boolean()),
    values: core.serialization.list(ScreenResponseAttributeValue),
});

export declare namespace ScreenResponseAttribute {
    export interface Raw {
        match_resolution: boolean;
        values: ScreenResponseAttributeValue.Raw[];
    }
}
