/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { WatchlistKeyValue } from "./WatchlistKeyValue";

export const WatchlistRiskIntelligenceValue: core.serialization.ObjectSchema<
    serializers.WatchlistRiskIntelligenceValue.Raw,
    Sayari.WatchlistRiskIntelligenceValue
> = core.serialization.object({
    list: core.serialization.string().optional(),
    type: core.serialization.string().optional(),
    score: core.serialization.number().optional(),
    reason: core.serialization.string().optional(),
    program: core.serialization.string().optional(),
    authority: core.serialization.string().optional(),
    fromDate: core.serialization.property("from_date", core.serialization.string().optional()),
    toDate: core.serialization.property("to_date", core.serialization.string().optional()),
    date: core.serialization.string().optional(),
    extra: core.serialization.list(WatchlistKeyValue).optional(),
});

export declare namespace WatchlistRiskIntelligenceValue {
    export interface Raw {
        list?: string | null;
        type?: string | null;
        score?: number | null;
        reason?: string | null;
        program?: string | null;
        authority?: string | null;
        from_date?: string | null;
        to_date?: string | null;
        date?: string | null;
        extra?: WatchlistKeyValue.Raw[] | null;
    }
}
