/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { Project } from "./Project";

export const CreateProjectResponse: core.serialization.ObjectSchema<
    serializers.CreateProjectResponse.Raw,
    Sayari.CreateProjectResponse
> = core.serialization.object({
    data: Project,
});

export declare namespace CreateProjectResponse {
    export interface Raw {
        data: Project.Raw;
    }
}
