/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";

export const IntKeyValue: core.serialization.ObjectSchema<serializers.IntKeyValue.Raw, SayariAnalyticsApi.IntKeyValue> =
    core.serialization.object({
        value: core.serialization.number(),
    });

export declare namespace IntKeyValue {
    interface Raw {
        value: number;
    }
}
