/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";
import { ProjectCounts } from "./ProjectCounts";

export const Project: core.serialization.ObjectSchema<serializers.Project.Raw, SayariAnalyticsApi.Project> =
    core.serialization.object({
        id: core.serialization.string(),
        label: core.serialization.string(),
        archived: core.serialization.boolean(),
        created: core.serialization.string(),
        updated: core.serialization.string(),
        counts: ProjectCounts,
    });

export declare namespace Project {
    interface Raw {
        id: string;
        label: string;
        archived: boolean;
        created: string;
        updated: string;
        counts: ProjectCounts.Raw;
    }
}
