/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";
import { RoleMember } from "./RoleMember";
import { Project } from "./Project";

export const ProjectWithMembers: core.serialization.ObjectSchema<
    serializers.ProjectWithMembers.Raw,
    SayariAnalyticsApi.ProjectWithMembers
> = core.serialization
    .object({
        members: core.serialization.list(RoleMember),
    })
    .extend(Project);

export declare namespace ProjectWithMembers {
    interface Raw extends Project.Raw {
        members: RoleMember.Raw[];
    }
}
