/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const Role: core.serialization.Schema<serializers.Role.Raw, Sayari.Role> = core.serialization.enum_([
    "viewer",
    "editor",
    "admin",
]);

export declare namespace Role {
    export type Raw = "viewer" | "editor" | "admin";
}
