/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { UpstreamTiers } from "./UpstreamTiers";

export const TierCountKeys: core.serialization.Schema<serializers.TierCountKeys.Raw, Sayari.TierCountKeys> =
    core.serialization.undiscriminatedUnion([UpstreamTiers, core.serialization.stringLiteral("totalCount")]);

export declare namespace TierCountKeys {
    export type Raw = UpstreamTiers.Raw | "totalCount";
}
