/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const TradeCount: core.serialization.ObjectSchema<serializers.TradeCount.Raw, Sayari.TradeCount> =
    core.serialization.object({
        receiverOf: core.serialization.property("receiver_of", core.serialization.number()),
        shipperOf: core.serialization.property("shipper_of", core.serialization.number()),
    });

export declare namespace TradeCount {
    interface Raw {
        receiver_of: number;
        shipper_of: number;
    }
}
