/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

/**
 * OK
 *
 * @example
 *     {}
 */
export interface EntitySummaryResponse extends SayariAnalyticsApi.EntityDetails {}
