/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
export const UsageInfo = core.serialization.object({
    entity: core.serialization.number().optional(),
    entitySummary: core.serialization.property("entity_summary", core.serialization.number().optional()),
    record: core.serialization.number().optional(),
    resolve: core.serialization.number().optional(),
    searchEntities: core.serialization.property("search_entities", core.serialization.number().optional()),
    searchRecords: core.serialization.property("search_records", core.serialization.number().optional()),
    searchTrade: core.serialization.property("search_trade", core.serialization.number().optional()),
    traversal: core.serialization.number().optional(),
});
