/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * The watchlist entity associated with a screening match, as stored at ingestion time. All attribute fields follow the Sayari ontology: each is an array of attribute records (WatchlistAttributeValue). All known attribute fields are always present in the response — fields with no data are returned as null rather than omitted. Empty arrays may also be returned for attributes with no values.
 */
export interface WatchlistEntityMatch {
    /** Unique identifier for the watchlist entity. */
    entityReferenceId: string;
    /** Entity type (e.g. "company", "person", "vessel"). */
    type: string;
    /** Miscellaneous information not covered by other attribute types. Records typically contain "value" and optional "type" and "extra" fields. */
    additionalInformation?: Sayari.WatchlistAttributeValue[];
    /** Physical location descriptions parsed via the Libpostal ontology. Each record contains "value" (full address string) plus structured sub-fields: "city", "state", "country", "postcode", "road", "house", "house_number", "unit", "x", "y", "near", "level", "building", "suburb", "island", "po_box", "entrance", "staircase", "category", "world_region", "city_district", "metro_station", "country_region", "state_district", "precision_code", "date", "from_date", "to_date", "language", "translated", "transliterated", and "extra" (array of WatchlistKeyValue with source attribution). */
    address?: Sayari.WatchlistAttributeValue[];
    /** Text or code (NAICS, NACE, ISIC, etc.) describing what the entity is legally permitted to do or produce. */
    businessPurpose?: Sayari.WatchlistAttributeValue[];
    /** Legal entity type in a given jurisdiction (e.g. "LLC", "Sociedad Anonima"). */
    companyType?: Sayari.WatchlistAttributeValue[];
    /** Contact information such as phone numbers, email addresses, or URLs. */
    contact?: Sayari.WatchlistAttributeValue[];
    /** Country affiliation through residence, nationality, registration, etc. */
    country?: Sayari.WatchlistAttributeValue[];
    /** Birth date of a person. Records typically contain a "value" field with the date string. */
    dateOfBirth?: Sayari.WatchlistAttributeValue[];
    /** Financial figures such as share capital (deprecated — use financials). */
    finances?: Sayari.WatchlistAttributeValue[];
    /** Financial information at a point in time (e.g. revenue, assets). */
    financials?: Sayari.WatchlistAttributeValue[];
    /** Gender of a person. */
    gender?: Sayari.WatchlistAttributeValue[];
    /** Placeholder attribute for data that does not fit any other attribute type. */
    generic?: Sayari.WatchlistAttributeValue[];
    /** ID numbers that uniquely identify an entity when value and type are both considered (e.g. registration number, tax ID). */
    identifier?: Sayari.WatchlistAttributeValue[];
    /** Numerical measurement of an entity dimension using a standard unit. */
    measurement?: Sayari.WatchlistAttributeValue[];
    /** Financial value of an asset (e.g. FOB, CIF values). */
    monetaryValue?: Sayari.WatchlistAttributeValue[];
    /** Entity name records. Each record contains at minimum a "value" field with the name string. */
    name?: Sayari.WatchlistAttributeValue[];
    /** Key life events for a person, usually temporal. */
    personStatus?: Sayari.WatchlistAttributeValue[];
    /** Title or designation associated with a relationship (e.g. "Secretary of the Board"). */
    position?: Sayari.WatchlistAttributeValue[];
    /** Risk or sanctions program data. Records contain structured fields (list, type, program, authority, from_date, to_date, score, reason, extra) — there is no "value" field on these records. */
    riskIntelligence?: Sayari.WatchlistRiskIntelligenceValue[];
    /** Risk factor umbrella values mapped from Risk Intelligence */
    riskFactors?: string[];
    /** Shareholding information. */
    shares?: Sayari.WatchlistAttributeValue[];
    /** Status of the entity (e.g. active, dissolved). */
    status?: Sayari.WatchlistAttributeValue[];
    /** Translated or transliterated name records. */
    translatedName?: Sayari.WatchlistAttributeValue[];
    /** Identifiers that are not unique on their own and require additional context to disambiguate. */
    weakIdentifier?: Sayari.WatchlistAttributeValue[];
    /** Risk events associated with the entity — ESG controversies, enforcement actions, adverse media, etc. Records may contain fields such as "category", "subcategory", "event_type", "title", "source_url", "credibility", "event_stage", "penalty_and_restriction", and "dismissal_and_clearance". */
    riskEvent?: Sayari.WatchlistAttributeValue[];
}
