/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * OK
 *
 * @example
 *     {
 *         offset: 0,
 *         limit: 1,
 *         size: {
 *             count: 3,
 *             qualifier: Sayari.CountQualifier.Eq
 *         },
 *         next: true,
 *         data: [{
 *                 id: "uWNWgzX-Kvp1j-WeXKmLQw",
 *                 label: "\u041E\u041E\u041E \"\u042D\u0420\u0411\u042D \u042D\u041B\u0415\u041A\u0422\u0420\u041E\u041C\u0415\u0414\u0418\u0426\u0418\u041D\"",
 *                 degree: 195,
 *                 entityUrl: "/v1/entity/uWNWgzX-Kvp1j-WeXKmLQw",
 *                 pep: false,
 *                 psaId: "4398046624552",
 *                 psaCount: 1,
 *                 sanctioned: false,
 *                 closed: false,
 *                 translatedLabel: "GESELLSCHAFT MIT BESCHRANKTER HAFTUNG \"ERBE ELEKTROMEDIZIN\"",
 *                 registrationDate: "2008-09-08",
 *                 type: Sayari.Entities.Company,
 *                 identifiers: [{
 *                         value: "7705856072",
 *                         type: Sayari.IdentifierType.RuInn,
 *                         label: "Ru Inn"
 *                     }, {
 *                         value: "5087746065578",
 *                         type: Sayari.IdentifierType.RuOgrn,
 *                         label: "Ru Ogrn"
 *                     }],
 *                 addresses: ["119270, , \u0413.\u041C\u041E\u0421\u041A\u0412\u0410, \u0423\u041B.\u0425\u0410\u041C\u041E\u0412\u041D\u0418\u0427\u0415\u0421\u041A\u0418\u0419 \u0412\u0410\u041B,\u0414.12,\u042D\u0422.2,\u041F\u041E\u041C.\u0425,\u041A\u041E\u041C.15,", "119270, \u0413\u041E\u0420\u041E\u0414 \u041C\u041E\u0421\u041A\u0412\u0410, \u0423\u041B. \u0425\u0410\u041C\u041E\u0412\u041D\u0418\u0427\u0415\u0421\u041A\u0418\u0419 \u0412\u0410\u041B, \u0414. 12, \u042D\u0422\u0410\u0416 2 \u041F\u041E\u041C \u0425 \u041A\u041E\u041C 15"],
 *                 countries: [Sayari.Country.Rus],
 *                 relationshipCount: {
 *                     [Sayari.Relationships.HasShareholder]: 1,
 *                     [Sayari.Relationships.NotifyPartyOf]: 133,
 *                     [Sayari.Relationships.HasDirector]: 1,
 *                     [Sayari.Relationships.ReceivesFrom]: 1,
 *                     [Sayari.Relationships.HasLegalRepresentative]: 1
 *                 },
 *                 tradeCount: {
 *                     "sent": 0,
 *                     "received": 192
 *                 },
 *                 sourceCount: {
 *                     "a9a18eeb901e4376c912e95dc05ceb78": {
 *                         count: 9,
 *                         label: "Russia Federal Tax Registry"
 *                     },
 *                     "66dfefb726ae00fde8f09f34c5578d35": {
 *                         count: 360,
 *                         label: "Russia Imports & Exports (January 2023 - Present)"
 *                     }
 *                 },
 *                 risk: {
 *                     [Sayari.Risk.ImportsBisHighPriorityItems]: {
 *                         value: 1,
 *                         metadata: {
 *                             "origin_shipment_product": [
 *                                 "853669"
 *                             ]
 *                         },
 *                         level: Sayari.RiskLevel.Elevated
 *                     },
 *                     [Sayari.Risk.ImportsBisHighPriorityItemsCriticalComponents]: {
 *                         value: 1,
 *                         metadata: {
 *                             "origin_shipment_product": [
 *                                 "854231"
 *                             ]
 *                         },
 *                         level: Sayari.RiskLevel.High
 *                     }
 *                 },
 *                 userAttributeCount: {},
 *                 userRecordCount: 0,
 *                 userRelatedEntitiesCount: 0,
 *                 userRelationshipCount: {},
 *                 relatedEntitiesCount: 195,
 *                 attributeCount: {
 *                     [Sayari.Attributes.Name]: 3,
 *                     [Sayari.Attributes.BusinessPurpose]: 10,
 *                     [Sayari.Attributes.Identifier]: 7,
 *                     [Sayari.Attributes.AdditionalInformation]: 2,
 *                     [Sayari.Attributes.Country]: 2,
 *                     [Sayari.Attributes.Shares]: 1,
 *                     [Sayari.Attributes.Status]: 1,
 *                     [Sayari.Attributes.Address]: 4,
 *                     [Sayari.Attributes.Financials]: 3
 *                 },
 *                 metadata: {
 *                     latestShipmentDate: "2024-07-10",
 *                     shipments: 6,
 *                     hsCodes: [{
 *                             key: "854231",
 *                             docCount: 6,
 *                             value: "Electronic integrated circuits; processors and controllers, whether or not combined with memories, converters, logic circuits, amplifiers, clock and timing circuits, or other circuits",
 *                             valueSimple: "Integrated Circuits"
 *                         }]
 *                 }
 *             }]
 *     }
 */
export interface BuyerSearchResponse extends Sayari.PaginatedResponse {
    offset: number;
    next: boolean;
    data: Sayari.SupplierOrBuyer[];
}
