/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface Shipment {
    id: string;
    type: string;
    buyer: Sayari.SourceOrDestinationEntity[];
    supplier: Sayari.SourceOrDestinationEntity[];
    arrivalDate?: string;
    departureDate?: string;
    departureAddress?: Sayari.ShipmentAddress;
    arrivalAddress?: Sayari.ShipmentAddress;
    arrivalCountry: Sayari.Country[];
    departureCountry: Sayari.Country[];
    transitCountry: Sayari.Country[];
    countries: Sayari.Country[];
    productOrigin: Sayari.Country[];
    monetaryValue: Sayari.MonetaryValue[];
    weight: Sayari.Weight[];
    identifier: Sayari.ShipmentIdentifier[];
    sources: Sayari.DataSource[];
    hsCodes: Sayari.HsCodeInfo[];
    productDescriptions: string[];
    /** The unique identifier for a record in the database */
    record: string;
}
