/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

export interface SourceOrDestinationEntity {
    /** Unique identifier of the entity */
    id: string;
    names: string[];
    /** [Risks](/sayari-library/ontology/risk-factors) */
    risks: Record<SayariAnalyticsApi.Risk, unknown>;
    /** [Business Purpose](/sayari-library/ontology/enumerated-types#business-purpose-standard) */
    businessPurpose: SayariAnalyticsApi.BusinessPurpose[];
    /** [Countries](/sayari-library/ontology/enumerated-types#country) */
    countries: SayariAnalyticsApi.Country[];
}
