/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface ProjectEntityRiskSummaryRiskFactor {
    id: string;
    label: string;
    value: Sayari.StringOrNumber;
    level: Sayari.RiskLevel;
    riskCategories: Sayari.ProjectRiskCategory[];
    sourceEntityIds: string[];
    networkPaths: Sayari.ProjectEntityRiskSummaryNetworkPath[][];
    metadata: Record<string, Sayari.StringOrNumber[]>[];
    riskIntelligence: Record<string, Sayari.StringOrNumber>[];
}
