/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface ProjectEntityMatchResponse {
    matchId: string;
    sayariEntityId: string;
    type: string;
    label: string;
    matchedAttributes: Sayari.MatchedAttributes;
    countries: string[];
    riskCategories: Sayari.ProjectRiskCategory[];
    riskFactors: Sayari.ProjectRiskFactor[];
    businessPurpose: Sayari.BusinessPurpose[];
    upstream: Sayari.UpstreamInfo;
    sources: Sayari.SourceField[];
    addresses: Sayari.Address[];
    hsCodes: string[];
    createdAt: string;
    updatedAt?: string;
    matchProfile?: Sayari.MatchProfileEnum;
    deletedAt?: string;
}
