/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface RiskChangeFactor {
    id: string;
    /** Timestamp of risk change detection */
    timestamp: string;
    changeType: Sayari.RiskChangeFactorChangeType;
}
