/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RiskChangeFactorChangeType = "added" | "removed";
export const RiskChangeFactorChangeType = {
    Added: "added",
    Removed: "removed",
} as const;
