/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const AdditionalInformationProperties: core.serialization.ObjectSchema<serializers.AdditionalInformationProperties.Raw, SayariAnalyticsApi.AdditionalInformationProperties>;
export declare namespace AdditionalInformationProperties {
    interface Raw {
        type?: string | null;
        value?: string | null;
    }
}
