/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as core from "../../../../core";
export const AttributeDetails = core.serialization.object({
    additionalInformation: core.serialization.property("additional_information", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).AdditionalInformationInfo; })).optional()),
    address: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).AddressInfo; })).optional(),
    businessPurpose: core.serialization.property("business_purpose", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).BusinessPurposeInfo; })).optional()),
    companyType: core.serialization.property("company_type", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).CompanyTypeInfo; })).optional()),
    contact: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).ContactInfo; })).optional(),
    country: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).CountryInfo; })).optional(),
    dateOfBirth: core.serialization.property("date_of_birth", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).DateOfBirthInfo; })).optional()),
    finances: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).FinancesInfo; })).optional(),
    financials: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).FinancialsInfo; })).optional(),
    gender: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).GenderInfo; })).optional(),
    generic: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).GenericInfo; })).optional(),
    identifier: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).IdentifierInfo; })).optional(),
    measurement: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).MeasurementInfo; })).optional(),
    monetaryValue: core.serialization.property("monetary_value", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).MonetaryValueInfo; })).optional()),
    name: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).NameInfo; })).optional(),
    personStatus: core.serialization.property("person_status", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).PersonStatusInfo; })).optional()),
    position: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).PositionInfo; })).optional(),
    riskIntelligence: core.serialization.property("risk_intelligence", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).RiskIntelligenceInfo; })).optional()),
    shares: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).SharesInfo; })).optional(),
    status: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).StatusInfo; })).optional(),
    translatedName: core.serialization.property("translated_name", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).TranslatedNameInfo; })).optional()),
    weakIdentifier: core.serialization.property("weak_identifier", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield import("../../..")).WeakIdentifierInfo; })).optional()),
});
