/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core/index.js";
export const CompanyTypeProperties = core.serialization.object({
    value: core.serialization.string().optional(),
});
