/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
export const CompanyStatus = core.serialization.enum_([
    "seized",
    "in_receivership",
    "registration_revoked",
    "opening",
    "dissolved",
    "active",
    "inactive",
    "closed",
    "closing",
    "registered",
    "incorporated",
    "under_external_control",
    "expired",
    "expanded",
    "terminated",
]);
