/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const GenericProperties: core.serialization.ObjectSchema<serializers.GenericProperties.Raw, SayariAnalyticsApi.GenericProperties>;
export declare namespace GenericProperties {
    interface Raw {
        type?: string | null;
        value?: string | null;
    }
}
