/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const NameInfo: core.serialization.ObjectSchema<serializers.NameInfo.Raw, SayariAnalyticsApi.NameInfo>;
export declare namespace NameInfo {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.NameData.Raw[];
    }
}
