/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const NameData: core.serialization.ObjectSchema<serializers.NameData.Raw, SayariAnalyticsApi.NameData>;
export declare namespace NameData {
    interface Raw extends serializers.AttributeData.Raw {
        properties: serializers.NameProperties.Raw;
    }
}
