/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const RiskIntelligenceInfo: core.serialization.ObjectSchema<serializers.RiskIntelligenceInfo.Raw, SayariAnalyticsApi.RiskIntelligenceInfo>;
export declare namespace RiskIntelligenceInfo {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.RiskIntelligenceData.Raw[];
    }
}
