/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const SharesInfo: core.serialization.ObjectSchema<serializers.SharesInfo.Raw, SayariAnalyticsApi.SharesInfo>;
export declare namespace SharesInfo {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.SharesData.Raw[];
    }
}
