/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core/index.js";
export const TranslationContext = core.serialization.enum_(["sayari_machine_translation", "pinyin", "google_translate"]);
