/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

/**
 * OK
 *
 * @example
 *     {
 *         offset: 0,
 *         limit: 1,
 *         size: {
 *             count: 64,
 *             qualifier: SayariAnalyticsApi.CountQualifier.Eq
 *         },
 *         next: true,
 *         data: [{
 *                 id: "mGq1lpuqKssNWTjIokuPeA",
 *                 label: "VICTORIA BECKHAM LIMITED",
 *                 degree: 67,
 *                 entityUrl: "/v1/entity/mGq1lpuqKssNWTjIokuPeA",
 *                 pep: false,
 *                 psaId: "695785012897",
 *                 psaCount: 3,
 *                 sanctioned: false,
 *                 closed: false,
 *                 companyType: "Stock Corporation - Out of State - Stock",
 *                 registrationDate: "Incorporated 2008-02-28",
 *                 latestStatus: {
 *                     status: "active",
 *                     date: "2023-08-29"
 *                 },
 *                 tradeCount: {
 *                     "sent": 41,
 *                     "received": 0
 *                 },
 *                 type: SayariAnalyticsApi.Entities.Company,
 *                 identifiers: [{
 *                         value: "06517802",
 *                         type: SayariAnalyticsApi.IdentifierType.UkCompanyNumber,
 *                         label: "Uk Company Number"
 *                     }, {
 *                         value: "6517802",
 *                         type: SayariAnalyticsApi.WeakIdentifierType.Unknown,
 *                         label: "Unknown"
 *                     }, {
 *                         value: "04781466",
 *                         type: SayariAnalyticsApi.IdentifierType.CaCorporateIdNum,
 *                         label: "Ca Corporate Id Num"
 *                     }],
 *                 addresses: ["202 HAMMERSMITH ROAD , LONDON , , UNITED KINGDOM , W6 7DN , GB", "Unit 33, Ransomes Dock Business Centre, 35-37 Parkgate Road, London SW11 4NP", "SAUNDERS BUILDING, 202 HAMMERSMITH ROAD, HAMMERSMITH, LONDON"],
 *                 countries: [SayariAnalyticsApi.Country.Gbr, SayariAnalyticsApi.Country.Usa],
 *                 relationshipCount: {
 *                     [SayariAnalyticsApi.Relationships.LinkedTo]: 3,
 *                     [SayariAnalyticsApi.Relationships.HasOfficer]: 2,
 *                     [SayariAnalyticsApi.Relationships.ShareholderOf]: 1,
 *                     [SayariAnalyticsApi.Relationships.HasShareholder]: 2,
 *                     [SayariAnalyticsApi.Relationships.HasRegisteredAgent]: 5,
 *                     [SayariAnalyticsApi.Relationships.ShipperOf]: 41,
 *                     [SayariAnalyticsApi.Relationships.HasDirector]: 11,
 *                     [SayariAnalyticsApi.Relationships.OwnerOf]: 3,
 *                     [SayariAnalyticsApi.Relationships.HasFounder]: 1,
 *                     [SayariAnalyticsApi.Relationships.ShipsTo]: 1
 *                 },
 *                 sourceCount: {
 *                     "2b618f1996252fe537a6d998ae14c9b2": {
 *                         count: 1,
 *                         label: "UK Corporate Registry Confirmation Statements"
 *                     },
 *                     "2b788dbdf9194ed5a5c309386a6516b1": {
 *                         count: 28,
 *                         label: "UK HM Revenue & Customs Traders Database"
 *                     },
 *                     "a447a7b622c4ead6e1caf94983dc2337": {
 *                         count: 6,
 *                         label: "USA California Secretary of State"
 *                     },
 *                     "ecdfb3f2ecc8c3797e77d5795a8066ef": {
 *                         count: 35,
 *                         label: "UK Corporate Registry"
 *                     },
 *                     "e5de7b52cc88ef4cd1a10e201bdf46ee": {
 *                         count: 41,
 *                         label: "Vietnam Imports & Exports (January 2023 - Present)"
 *                     },
 *                     "2a4fe9a14e332c8f9ded1f8a457c2b89": {
 *                         count: 36,
 *                         label: "UK Land Commercial and Corporate Ownership Data (CCOD)"
 *                     },
 *                     "4ea8bac1bed868e1510ffd21842e9551": {
 *                         count: 69,
 *                         label: "UK Persons with Significant Control"
 *                     }
 *                 },
 *                 risk: {
 *                     [SayariAnalyticsApi.Risk.BaselAml]: {
 *                         value: 4.63,
 *                         metadata: {
 *                             "country": [
 *                                 "USA"
 *                             ]
 *                         },
 *                         level: SayariAnalyticsApi.RiskLevel.Relevant
 *                     },
 *                     [SayariAnalyticsApi.Risk.CpiScore]: {
 *                         value: 67,
 *                         metadata: {
 *                             "country": [
 *                                 "USA"
 *                             ]
 *                         },
 *                         level: SayariAnalyticsApi.RiskLevel.Relevant
 *                     }
 *                 },
 *                 userAttributeCount: {},
 *                 userRecordCount: 0,
 *                 userRelatedEntitiesCount: 0,
 *                 userRelationshipCount: {},
 *                 relatedEntitiesCount: 67,
 *                 attributeCount: {
 *                     [SayariAnalyticsApi.Attributes.CompanyType]: 2,
 *                     [SayariAnalyticsApi.Attributes.Name]: 2,
 *                     [SayariAnalyticsApi.Attributes.BusinessPurpose]: 4,
 *                     [SayariAnalyticsApi.Attributes.Identifier]: 3,
 *                     [SayariAnalyticsApi.Attributes.AdditionalInformation]: 106,
 *                     [SayariAnalyticsApi.Attributes.Country]: 8,
 *                     [SayariAnalyticsApi.Attributes.Status]: 5,
 *                     [SayariAnalyticsApi.Attributes.Address]: 7
 *                 },
 *                 referenceId: "ecdfb3f2ecc8c3797e77d5795a8066ef/06517802/1540252800000:4a34442eccf1622995130b194a5d50e7",
 *                 coordinates: [{
 *                         lat: 51.49323,
 *                         lng: -0.22207,
 *                         address: "202 HAMMERSMITH ROAD , LONDON , , UNITED KINGDOM , W6 7DN , GB"
 *                     }, {
 *                         lat: 51.47943,
 *                         lng: -0.16859,
 *                         address: "Unit 33, Ransomes Dock Business Centre, 35-37 Parkgate Road, London SW11 4NP"
 *                     }, {
 *                         lat: 51.49323,
 *                         lng: -0.22207,
 *                         address: "SAUNDERS BUILDING, 202 HAMMERSMITH ROAD, HAMMERSMITH, LONDON"
 *                     }, {
 *                         lat: 51.47898,
 *                         lng: -0.16784,
 *                         address: "Ransome's Dock, 35-37 Parkgate Road, London, SW11 4NP"
 *                     }, {
 *                         lat: 51.493080000000006,
 *                         lng: -0.22138000000000002,
 *                         address: "Hammersmith Road, London, W6 7DN"
 *                     }, {
 *                         lat: 51.49291,
 *                         lng: -0.22579,
 *                         address: "202 HAMMERSMITH ROAD UNITED KINGDOM"
 *                     }],
 *                 matches: {
 *                     "name": ["<em>VICTORIA</em> <em>BECKHAM</em> <em>LIMITED</em>", "<em>BECKHAM</em> VENTURES <em>LIMITED</em>", "<em>VICTORIA</em> <em>BECKHAM</em> LIMITED", "<em>BECKHAM</em> VENTURES LIMITED"]
 *                 }
 *             }]
 *     }
 */
export interface EntitySearchResponse extends SayariAnalyticsApi.PaginatedResponse {
    offset: number;
    next: boolean;
    data: SayariAnalyticsApi.SearchResults[];
}
