/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         field: "custom_phone",
 *         value: "+1-555-123-4567",
 *         matchResolution: false
 *     }
 */
export interface CreateProjectEntityAttributeRequest {
    field: string;
    value: string;
    matchResolution: boolean;
}
