/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateProjectEntityAttributeResponseData {
    id: string;
    field: string;
    value: string;
    matchResolution: boolean;
}
