/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const TraversalRelationshipData: core.serialization.ObjectSchema<serializers.TraversalRelationshipData.Raw, SayariAnalyticsApi.TraversalRelationshipData>;
export declare namespace TraversalRelationshipData {
    interface Raw {
        values: serializers.RelationshipInfo.Raw[];
        last_observed?: string | null;
    }
}
