/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const ExpiresIn: core.serialization.Schema<serializers.ExpiresIn.Raw, SayariAnalyticsApi.ExpiresIn>;
export declare namespace ExpiresIn {
    type Raw = number;
}
