/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const RecordSearchResults: core.serialization.ObjectSchema<serializers.RecordSearchResults.Raw, SayariAnalyticsApi.RecordSearchResults>;
export declare namespace RecordSearchResults {
    interface Raw extends serializers.PaginatedResponse.Raw {
        offset: number;
        next: boolean;
        data: serializers.RecordDetails.Raw[];
    }
}
