/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         clientId: "your client_id here",
 *         clientSecret: "your client_secret here"
 *     }
 */
export interface GetToken {
    clientId: string;
    clientSecret: string;
}
