/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface UsageResponse {
    /** Usage information for each endpoint */
    usage: Sayari.UsageInfo;
    /** The start date of the returned usage information. */
    from: string;
    /** The end date of the returned usage information. */
    to: string;
}
