/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";

export const BadGatewayResponse: core.serialization.Schema<
    serializers.BadGatewayResponse.Raw,
    SayariAnalyticsApi.BadGatewayResponse
> = core.serialization.unknown();

export declare namespace BadGatewayResponse {
    type Raw = unknown;
}
