/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const ConnectionErrorResponse: core.serialization.Schema<
    serializers.ConnectionErrorResponse.Raw,
    Sayari.ConnectionErrorResponse
> = core.serialization.unknown();

export declare namespace ConnectionErrorResponse {
    export type Raw = unknown;
}
