/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TradeTraversalProduct {
    hsCode: string;
    minDate: string;
    maxDate: string;
    arrivalCountries: string[];
    departureCountries: string[];
}
