/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface TradeTraversalPathSegment {
    src: string;
    dst: string;
    hsCodes?: string[];
    products?: Sayari.TradeTraversalProduct[];
}
