/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { AttributeProperties } from "./AttributeProperties";

export const AttributeResponseData: core.serialization.ObjectSchema<
    serializers.AttributeResponseData.Raw,
    Sayari.AttributeResponseData
> = core.serialization.object({
    value: core.serialization.unknown(),
    properties: core.serialization.list(AttributeProperties),
});

export declare namespace AttributeResponseData {
    export interface Raw {
        value?: unknown;
        properties: AttributeProperties.Raw[];
    }
}
