/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import * as SayariAnalyticsApi from "../../../../../api";
import * as core from "../../../../../core";

export const SearchSuppliers: core.serialization.Schema<
    serializers.SearchSuppliers.Raw,
    Omit<SayariAnalyticsApi.SearchSuppliers, "limit" | "offset">
> = core.serialization.object({
    q: core.serialization.string(),
    filter: core.serialization.lazyObject(async () => (await import("../../../..")).TradeFilterList).optional(),
    facets: core.serialization.boolean().optional(),
    advanced: core.serialization.boolean().optional(),
});

export declare namespace SearchSuppliers {
    interface Raw {
        q: string;
        filter?: serializers.TradeFilterList.Raw | null;
        facets?: boolean | null;
        advanced?: boolean | null;
    }
}
