/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * @example
 *     {
 *         filters: {
 *             id: [Sayari.Relationships.AuditorOf]
 *         },
 *         data: [{
 *                 id: Sayari.Relationships.AuditorOf,
 *                 label: "Auditor Of",
 *                 description: "Companies audited by this entity",
 *                 comment: "The source entity is reported to be the auditor of a company",
 *                 type: "forward",
 *                 inverse: Sayari.Relationships.HasAuditor,
 *                 between: [{
 *                         from: Sayari.Entities.Person,
 *                         to: Sayari.Entities.Company
 *                     }, {
 *                         from: Sayari.Entities.Company,
 *                         to: Sayari.Entities.Company
 *                     }],
 *                 attributes: [Sayari.Attributes.AdditionalInformation, Sayari.Attributes.Position]
 *             }],
 *         totalCount: 1234
 *     }
 */
export interface GetOntologyRelationshipsResponse {
    filters: Sayari.OntologyRelationshipsFilters;
    data: Sayari.OntologyRelationship[];
    totalCount: number;
}
