/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * @example
 *     {
 *         filters: {
 *             code: ["1503"]
 *         },
 *         data: [{
 *                 code: "1503",
 *                 shortDescription: "Lard & tallow products",
 *                 longDescription: "Lard stearin, lard oil, oleostearin, oleo-oil and tallow oil; not emulsified or mixed or otherwise prepared"
 *             }],
 *         totalCount: 1234
 *     }
 */
export interface GetOntologyHsCodesResponse {
    filters: Sayari.OntologyHsCodesFilters;
    data: Sayari.OntologyHsCode[];
    totalCount: number;
}
