/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Will always be "sayari.com"
 */
export type Audience = "sayari.com";

export const Audience = {
    Sayari: "sayari.com",
} as const;
