/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request made in an unacceptable state due to an invalid Accept header.
 */
export interface NotAcceptableResponse {
    status: number;
    message: string[];
    success: boolean;
}
