/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request made with an unsupported HTTP method.
 */
export interface NotFoundResponse {
    status: number;
    message: string[];
    success: boolean;
}
