/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const EntityRelationships: core.serialization.ObjectSchema<
    serializers.EntityRelationships.Raw,
    SayariAnalyticsApi.EntityRelationships
> = core.serialization
    .object({
        data: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).RelationshipData)
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).PaginatedResponse));

export declare namespace EntityRelationships {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.RelationshipData.Raw[];
    }
}
