/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const EntityAddresses: core.serialization.Schema<
    serializers.EntityAddresses.Raw,
    SayariAnalyticsApi.EntityAddresses
> = core.serialization.string();

export declare namespace EntityAddresses {
    type Raw = string;
}
