/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";

export const ReferencedByDataType: core.serialization.Schema<
    serializers.ReferencedByDataType.Raw,
    SayariAnalyticsApi.ReferencedByDataType
> = core.serialization.enum_(["about", "mentions"]);

export declare namespace ReferencedByDataType {
    type Raw = "about" | "mentions";
}
