/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const RiskData: core.serialization.ObjectSchema<serializers.RiskData.Raw, SayariAnalyticsApi.RiskData> =
    core.serialization.object({
        value: core.serialization.unknown(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        level: core.serialization.lazy(async () => (await import("../../..")).RiskLevel),
    });

export declare namespace RiskData {
    interface Raw {
        value?: unknown;
        metadata: Record<string, unknown>;
        level: serializers.RiskLevel.Raw;
    }
}
