/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api/index";
import * as core from "../../../../core";

export const SearchField: core.serialization.Schema<serializers.SearchField.Raw, SayariAnalyticsApi.SearchField> =
    core.serialization.enum_(["name", "identifier", "address", "business_purpose", "date_of_birth", "contact"]);

export declare namespace SearchField {
    type Raw = "name" | "identifier" | "address" | "business_purpose" | "date_of_birth" | "contact";
}
