/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../..";

/**
 * OK
 *
 * @example
 *     {
 *         entities: ["mGq1lpuqKssNWTjIokuPeA", "ekPP386sHXHREr15-iVgvw"],
 *         data: [{
 *                 source: "mGq1lpuqKssNWTjIokuPeA",
 *                 target: {
 *                     id: "ekPP386sHXHREr15-iVgvw",
 *                     label: "BECKHAM RETAIL LIMITED",
 *                     degree: 6,
 *                     entityUrl: "/v1/entity/ekPP386sHXHREr15-iVgvw",
 *                     pep: false,
 *                     psaCount: 0,
 *                     sanctioned: false,
 *                     closed: false,
 *                     companyType: "Private Limited Company",
 *                     registrationDate: "Incorporated 2013-08-22",
 *                     latestStatus: {
 *                         status: "active"
 *                     },
 *                     type: SayariAnalyticsApi.Entities.Company,
 *                     identifiers: [{
 *                             value: "08661308",
 *                             type: "uk_company_number",
 *                             label: "Uk Company Number"
 *                         }],
 *                     addresses: ["202 HAMMERSMITH ROAD, LONDON, W6 7DN"],
 *                     countries: [SayariAnalyticsApi.Country.Gbr],
 *                     relationshipCount: {
 *                         [SayariAnalyticsApi.Relationships.HasDirector]: 4,
 *                         [SayariAnalyticsApi.Relationships.HasShareholder]: 1,
 *                         [SayariAnalyticsApi.Relationships.LinkedTo]: 1,
 *                         [SayariAnalyticsApi.Relationships.HasRegisteredAgent]: 1
 *                     },
 *                     sourceCount: {
 *                         "ecdfb3f2ecc8c3797e77d5795a8066ef": {
 *                             count: 32,
 *                             label: "UK Corporate Registry"
 *                         },
 *                         "2b618f1996252fe537a6d998ae14c9b2": {
 *                             count: 1,
 *                             label: "UK Corporate Registry Confirmation Statements"
 *                         },
 *                         "4ea8bac1bed868e1510ffd21842e9551": {
 *                             count: 18,
 *                             label: "UK Persons with Significant Control"
 *                         }
 *                     },
 *                     risk: {},
 *                     userAttributeCounts: {},
 *                     userRecordCount: 0,
 *                     userRelatedEntitiesCount: 0,
 *                     userRelationshipCount: {},
 *                     relatedEntitiesCount: 6,
 *                     attributeCounts: {
 *                         "company_type": 1,
 *                         "name": 2,
 *                         "business_purpose": 2,
 *                         "identifier": 1,
 *                         "country": 2,
 *                         "status": 2,
 *                         "address": 1
 *                     }
 *                 },
 *                 path: [{
 *                         field: "shareholder_of",
 *                         entity: {
 *                             id: "ekPP386sHXHREr15-iVgvw",
 *                             label: "BECKHAM RETAIL LIMITED",
 *                             degree: 6,
 *                             entityUrl: "/v1/entity/ekPP386sHXHREr15-iVgvw",
 *                             pep: false,
 *                             psaCount: 0,
 *                             sanctioned: false,
 *                             closed: false,
 *                             companyType: "Private Limited Company",
 *                             registrationDate: "Incorporated 2013-08-22",
 *                             latestStatus: {
 *                                 status: "active"
 *                             },
 *                             type: SayariAnalyticsApi.Entities.Company,
 *                             identifiers: [{
 *                                     value: "08661308",
 *                                     type: "uk_company_number",
 *                                     label: "Uk Company Number"
 *                                 }],
 *                             addresses: ["202 HAMMERSMITH ROAD, LONDON, W6 7DN"],
 *                             countries: [SayariAnalyticsApi.Country.Gbr],
 *                             relationshipCount: {
 *                                 [SayariAnalyticsApi.Relationships.HasDirector]: 4,
 *                                 [SayariAnalyticsApi.Relationships.HasShareholder]: 1,
 *                                 [SayariAnalyticsApi.Relationships.LinkedTo]: 1,
 *                                 [SayariAnalyticsApi.Relationships.HasRegisteredAgent]: 1
 *                             },
 *                             sourceCount: {
 *                                 "ecdfb3f2ecc8c3797e77d5795a8066ef": {
 *                                     count: 32,
 *                                     label: "UK Corporate Registry"
 *                                 },
 *                                 "2b618f1996252fe537a6d998ae14c9b2": {
 *                                     count: 1,
 *                                     label: "UK Corporate Registry Confirmation Statements"
 *                                 },
 *                                 "4ea8bac1bed868e1510ffd21842e9551": {
 *                                     count: 18,
 *                                     label: "UK Persons with Significant Control"
 *                                 }
 *                             },
 *                             risk: {},
 *                             userAttributeCounts: {},
 *                             userRecordCount: 0,
 *                             userRelatedEntitiesCount: 0,
 *                             userRelationshipCount: {},
 *                             relatedEntitiesCount: 6,
 *                             attributeCounts: {
 *                                 "company_type": 1,
 *                                 "name": 2,
 *                                 "business_purpose": 2,
 *                                 "identifier": 1,
 *                                 "country": 2,
 *                                 "status": 2,
 *                                 "address": 1
 *                             }
 *                         },
 *                         relationships: {
 *                             [SayariAnalyticsApi.Relationships.LinkedTo]: {
 *                                 values: [{
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/08661308/1560176240192",
 *                                         acquisitionDate: "2019-06-10",
 *                                         attributes: {
 *                                             [SayariAnalyticsApi.Attributes.Position]: [{
 *                                                     value: "Has right to appoint and remove directors"
 *                                                 }]
 *                                         }
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1586822400000",
 *                                         acquisitionDate: "2020-04-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1601424000000",
 *                                         acquisitionDate: "2020-09-30",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1616630400000",
 *                                         acquisitionDate: "2021-03-25",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1634169600000",
 *                                         acquisitionDate: "2021-10-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1649894400000",
 *                                         acquisitionDate: "2022-04-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1667433600000",
 *                                         acquisitionDate: "2022-11-03",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1675123200000",
 *                                         acquisitionDate: "2023-01-31",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1676505600000",
 *                                         acquisitionDate: "2023-02-16",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1678320000000",
 *                                         acquisitionDate: "2023-03-09",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1680566400000",
 *                                         acquisitionDate: "2023-04-04",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1682899200000",
 *                                         acquisitionDate: "2023-05-01",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1685577600000",
 *                                         acquisitionDate: "2023-06-01",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1689033600000",
 *                                         acquisitionDate: "2023-07-11",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1692662400000",
 *                                         acquisitionDate: "2023-08-22",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1694476800000",
 *                                         acquisitionDate: "2023-09-12",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1696896000000",
 *                                         acquisitionDate: "2023-10-10",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1699488000000",
 *                                         acquisitionDate: "2023-11-09",
 *                                         attributes: {}
 *                                     }]
 *                             },
 *                             [SayariAnalyticsApi.Relationships.ShareholderOf]: {
 *                                 values: [{
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/08661308/1560176240192",
 *                                         acquisitionDate: "2019-06-10",
 *                                         attributes: {
 *                                             [SayariAnalyticsApi.Attributes.Position]: [{
 *                                                     value: "Has right to appoint and remove directors"
 *                                                 }]
 *                                         }
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1586822400000",
 *                                         acquisitionDate: "2020-04-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1601424000000",
 *                                         acquisitionDate: "2020-09-30",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1616630400000",
 *                                         acquisitionDate: "2021-03-25",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1634169600000",
 *                                         acquisitionDate: "2021-10-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1649894400000",
 *                                         acquisitionDate: "2022-04-14",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1667433600000",
 *                                         acquisitionDate: "2022-11-03",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1675123200000",
 *                                         acquisitionDate: "2023-01-31",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1676505600000",
 *                                         acquisitionDate: "2023-02-16",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1678320000000",
 *                                         acquisitionDate: "2023-03-09",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1680566400000",
 *                                         acquisitionDate: "2023-04-04",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1682899200000",
 *                                         acquisitionDate: "2023-05-01",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1685577600000",
 *                                         acquisitionDate: "2023-06-01",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1689033600000",
 *                                         acquisitionDate: "2023-07-11",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1692662400000",
 *                                         acquisitionDate: "2023-08-22",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1694476800000",
 *                                         acquisitionDate: "2023-09-12",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1696896000000",
 *                                         acquisitionDate: "2023-10-10",
 *                                         attributes: {}
 *                                     }, {
 *                                         record: "4ea8bac1bed868e1510ffd21842e9551/ef8cbb3fcc71d09f098f00728df231e8/1699488000000",
 *                                         acquisitionDate: "2023-11-09",
 *                                         attributes: {}
 *                                     }]
 *                             }
 *                         }
 *                     }]
 *             }]
 *     }
 */
export interface ShortestPathResponse {
    entities: string[];
    data: SayariAnalyticsApi.ShortestPathData[];
}
