/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export type TraversalRiskCategory =
    /**
     * Matches specific risk category */
    | Sayari.RiskCategories[]
    /**
     * Matches a custom risk category */
    | string;
