/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

export interface TraversalPath {
    field: string;
    entity: SayariAnalyticsApi.EntityDetails;
    relationships: Record<SayariAnalyticsApi.Relationships, SayariAnalyticsApi.TraversalRelationshipData | undefined>;
}
