/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as SayariAnalyticsApi from "../../../index";

export class NotFound extends errors.SayariAnalyticsApiError {
    constructor(body: SayariAnalyticsApi.NotFoundResponse) {
        super({
            message: "NotFound",
            statusCode: 404,
            body: body,
        });
        Object.setPrototypeOf(this, NotFound.prototype);
    }
}
