/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../../index";

/**
 * @example
 *     {
 *         id: ["e85d865943ee6d8369307569d2ad9de0"],
 *         country: ["XXX"],
 *         sourceType: ["adverse_media_/_negative_news_data"]
 *     }
 */
export interface GetOntologySourcesRequest {
    /**
     * Source Id filter.
     */
    id?: string[];
    /**
     * Source country filter.
     */
    country?: Sayari.Country[];
    /**
     * Source type filter.
     */
    sourceType?: string[];
}
