/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: ["usa_&_canada"]
 *     }
 */
export interface GetOntologyRegionsRequest {
    /**
     * Region Id filter.
     */
    id?: string[];
}
