/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: ["adverse_media_/_negative_news_data"]
 *     }
 */
export interface GetOntologySourceTypesRequest {
    /**
     * Source type Id filter.
     */
    id?: string[];
}
