/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const HistoryInfo: core.serialization.ObjectSchema<serializers.HistoryInfo.Raw, SayariAnalyticsApi.HistoryInfo> =
    core.serialization.object({
        user: core.serialization.string(),
        environment: core.serialization.string(),
        event: core.serialization.string(),
        data: core.serialization.lazy(async () => (await import("../../..")).EventInfo),
        timestamp: core.serialization.string(),
    });

export declare namespace HistoryInfo {
    interface Raw {
        user: string;
        environment: string;
        event: string;
        data: serializers.EventInfo.Raw;
        timestamp: string;
    }
}
