/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const UsageInfo: core.serialization.ObjectSchema<serializers.UsageInfo.Raw, Sayari.UsageInfo> =
    core.serialization.object({
        entity: core.serialization.number().optional(),
        record: core.serialization.number().optional(),
        resolve: core.serialization.number().optional(),
        search: core.serialization.number().optional(),
        tradeTraversal: core.serialization.property("trade_traversal", core.serialization.number().optional()),
        traversal: core.serialization.number().optional(),
    });

export declare namespace UsageInfo {
    export interface Raw {
        entity?: number | null;
        record?: number | null;
        resolve?: number | null;
        search?: number | null;
        trade_traversal?: number | null;
        traversal?: number | null;
    }
}
