/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const UsageResponse: core.serialization.ObjectSchema<
    serializers.UsageResponse.Raw,
    SayariAnalyticsApi.UsageResponse
> = core.serialization.object({
    usage: core.serialization.lazyObject(async () => (await import("../../..")).UsageInfo),
    from: core.serialization.string(),
    to: core.serialization.string(),
});

export declare namespace UsageResponse {
    interface Raw {
        usage: serializers.UsageInfo.Raw;
        from: string;
        to: string;
    }
}
