/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProfileEnum = "corporate" | "suppliers" | "search";

export const ProfileEnum = {
    Corporate: "corporate",
    Suppliers: "suppliers",
    Search: "search",
} as const;
