/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../../index";
export interface AddressProperties {
    building?: string;
    category?: string;
    city?: string;
    cityDistrict?: string;
    country?: string;
    countryRegion?: string;
    entrance?: string;
    house?: string;
    houseNumber?: string;
    island?: string;
    language?: SayariAnalyticsApi.Language;
    level?: string;
    metroStation?: string;
    near?: string;
    poBox?: string;
    postcode?: string;
    precisionCode?: string;
    road?: string;
    staircase?: string;
    state?: string;
    stateDistrict?: string;
    suburb?: string;
    translated?: string;
    transliterated?: string;
    type?: SayariAnalyticsApi.AddressType;
    unit?: string;
    value?: string;
    worldRegion?: string;
    x?: number;
    y?: number;
}
