/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../..";
export interface BusinessPurposeProperties {
    code?: string;
    standard?: SayariAnalyticsApi.BusinessPurposeStandard;
    value?: string;
}
