/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const Entities = {
    LegalMatter: "legal_matter",
    Company: "company",
    Shipment: "shipment",
    Generic: "generic",
    Vessel: "vessel",
    Property: "property",
    IntellectualProperty: "intellectual_property",
    Person: "person",
    Security: "security",
    Tradename: "tradename",
    Unknown: "unknown",
    Aircraft: "aircraft",
};
