/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../../index";
/**
 * The financial value of an asset (e.g. FOB, CIF)
 */
export interface MonetaryValueInfo extends SayariAnalyticsApi.PaginatedResponse {
    data: SayariAnalyticsApi.MonetaryValueData[];
}
