/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../../index";
export interface RiskIntelligenceProperties {
    authority?: string;
    list?: string;
    program?: string;
    reason?: string;
    type: SayariAnalyticsApi.Tag;
}
