/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../../index";
/**
 * The status of an entity.
 */
export interface StatusInfo extends SayariAnalyticsApi.PaginatedResponse {
    data: SayariAnalyticsApi.StatusData[];
}
