/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A map of fields appearing in the audit logs for this event
 */
export declare type EventInfo = Record<string, unknown>;
