/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Request made in an unacceptable state. This is most commonly due to parameter validation errors.
 */
export interface NotAcceptableResponse {
    status: number;
    message: string[];
    success: boolean;
}
