/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { ResourceNotificationData } from "./ResourceNotificationData";

export const ResourceNotificationsResponse: core.serialization.ObjectSchema<
    serializers.ResourceNotificationsResponse.Raw,
    Sayari.ResourceNotificationsResponse
> = core.serialization.object({
    offset: core.serialization.number(),
    limit: core.serialization.number(),
    next: core.serialization.boolean(),
    data: core.serialization.list(ResourceNotificationData),
});

export declare namespace ResourceNotificationsResponse {
    export interface Raw {
        offset: number;
        limit: number;
        next: boolean;
        data: ResourceNotificationData.Raw[];
    }
}
