/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const AddressData: core.serialization.ObjectSchema<serializers.AddressData.Raw, SayariAnalyticsApi.AddressData> =
    core.serialization
        .object({
            properties: core.serialization.lazyObject(async () => (await import("../../..")).AddressProperties),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).AttributeData));

export declare namespace AddressData {
    interface Raw extends serializers.AttributeData.Raw {
        properties: serializers.AddressProperties.Raw;
    }
}
