/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const Attributes: core.serialization.Schema<serializers.Attributes.Raw, SayariAnalyticsApi.Attributes> =
    core.serialization.enum_([
        "address",
        "measurement",
        "weak_identifier",
        "country",
        "gender",
        "generic",
        "shares",
        "identifier",
        "status",
        "date_of_birth",
        "finances",
        "additional_information",
        "position",
        "contact",
        "business_purpose",
        "risk_intelligence",
        "translated_name",
        "name",
        "person_status",
        "monetary_value",
        "company_type",
        "financials",
    ]);

export declare namespace Attributes {
    type Raw =
        | "address"
        | "measurement"
        | "weak_identifier"
        | "country"
        | "gender"
        | "generic"
        | "shares"
        | "identifier"
        | "status"
        | "date_of_birth"
        | "finances"
        | "additional_information"
        | "position"
        | "contact"
        | "business_purpose"
        | "risk_intelligence"
        | "translated_name"
        | "name"
        | "person_status"
        | "monetary_value"
        | "company_type"
        | "financials";
}
