/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const DateOfBirthProperties: core.serialization.ObjectSchema<
    serializers.DateOfBirthProperties.Raw,
    SayariAnalyticsApi.DateOfBirthProperties
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace DateOfBirthProperties {
    interface Raw {
        value: string;
    }
}
