/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const Entities: core.serialization.Schema<serializers.Entities.Raw, Sayari.Entities> = core.serialization.enum_([
    "unknown",
    "tradename",
    "legal_matter",
    "generic",
    "shipment",
    "intellectual_property",
    "aircraft",
    "vessel",
    "person",
    "security",
    "property",
    "company",
]);

export declare namespace Entities {
    type Raw =
        | "unknown"
        | "tradename"
        | "legal_matter"
        | "generic"
        | "shipment"
        | "intellectual_property"
        | "aircraft"
        | "vessel"
        | "person"
        | "security"
        | "property"
        | "company";
}
