/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { FinancesData } from "./FinancesData";
import { PaginatedResponse } from "../../baseTypes/types/PaginatedResponse";

export const FinancesInfo: core.serialization.ObjectSchema<serializers.FinancesInfo.Raw, Sayari.FinancesInfo> =
    core.serialization
        .object({
            data: core.serialization.list(FinancesData),
            next: core.serialization.unknown().optional(),
            offset: core.serialization.number().optional(),
        })
        .extend(PaginatedResponse);

export declare namespace FinancesInfo {
    export interface Raw extends PaginatedResponse.Raw {
        data: FinancesData.Raw[];
        next?: unknown | null;
        offset?: number | null;
    }
}
