/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const FinancialsProperties: core.serialization.ObjectSchema<
    serializers.FinancialsProperties.Raw,
    SayariAnalyticsApi.FinancialsProperties
> = core.serialization.object({
    assets: core.serialization.number().optional(),
    currency: core.serialization.lazy(async () => (await import("../../..")).Currency).optional(),
    employees: core.serialization.number().optional(),
    liabilities: core.serialization.number().optional(),
    netIncome: core.serialization.property("net_income", core.serialization.number().optional()),
    paidUpCapital: core.serialization.property("paid_up_capital", core.serialization.number().optional()),
    registeredCapital: core.serialization.property("registered_capital", core.serialization.number().optional()),
    revenue: core.serialization.number().optional(),
});

export declare namespace FinancialsProperties {
    interface Raw {
        assets?: number | null;
        currency?: serializers.Currency.Raw | null;
        employees?: number | null;
        liabilities?: number | null;
        net_income?: number | null;
        paid_up_capital?: number | null;
        registered_capital?: number | null;
        revenue?: number | null;
    }
}
