/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const FinanceType: core.serialization.Schema<serializers.FinanceType.Raw, Sayari.FinanceType> =
    core.serialization.enum_([
        "authorized_capital",
        "paid_up_capital",
        "registered_capital",
        "share_amount",
        "share_percentage",
        "subscribed_capital",
    ]);

export declare namespace FinanceType {
    type Raw =
        | "authorized_capital"
        | "paid_up_capital"
        | "registered_capital"
        | "share_amount"
        | "share_percentage"
        | "subscribed_capital";
}
