/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const GenderInfo: core.serialization.ObjectSchema<serializers.GenderInfo.Raw, SayariAnalyticsApi.GenderInfo> =
    core.serialization
        .object({
            data: core.serialization.list(
                core.serialization.lazyObject(async () => (await import("../../..")).GenderData)
            ),
            next: core.serialization.unknown().optional(),
            offset: core.serialization.number().optional(),
        })
        .extend(core.serialization.lazyObject(async () => (await import("../../..")).PaginatedResponse));

export declare namespace GenderInfo {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.GenderData.Raw[];
        next?: unknown | null;
        offset?: number | null;
    }
}
