/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { IdentifierData } from "./IdentifierData";
import { PaginatedResponse } from "../../baseTypes/types/PaginatedResponse";

export const IdentifierInfo: core.serialization.ObjectSchema<serializers.IdentifierInfo.Raw, Sayari.IdentifierInfo> =
    core.serialization
        .object({
            data: core.serialization.list(IdentifierData),
            next: core.serialization.unknown().optional(),
            offset: core.serialization.number().optional(),
        })
        .extend(PaginatedResponse);

export declare namespace IdentifierInfo {
    export interface Raw extends PaginatedResponse.Raw {
        data: IdentifierData.Raw[];
        next?: unknown | null;
        offset?: number | null;
    }
}
