/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const MonetaryValueData: core.serialization.ObjectSchema<
    serializers.MonetaryValueData.Raw,
    SayariAnalyticsApi.MonetaryValueData
> = core.serialization
    .object({
        properties: core.serialization.lazyObject(async () => (await import("../../..")).MonetaryValueProperties),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).AttributeData));

export declare namespace MonetaryValueData {
    interface Raw extends serializers.AttributeData.Raw {
        properties: serializers.MonetaryValueProperties.Raw;
    }
}
