/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const NameProperties: core.serialization.ObjectSchema<
    serializers.NameProperties.Raw,
    SayariAnalyticsApi.NameProperties
> = core.serialization.object({
    context: core.serialization.string().optional(),
    language: core.serialization.lazy(async () => (await import("../../..")).Language).optional(),
    translated: core.serialization.string().optional(),
    transliterated: core.serialization.string().optional(),
    value: core.serialization.string(),
});

export declare namespace NameProperties {
    interface Raw {
        context?: string | null;
        language?: serializers.Language.Raw | null;
        translated?: string | null;
        transliterated?: string | null;
        value: string;
    }
}
