/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const PositionInfo: core.serialization.ObjectSchema<
    serializers.PositionInfo.Raw,
    SayariAnalyticsApi.PositionInfo
> = core.serialization
    .object({
        data: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../..")).PositionData)
        ),
        next: core.serialization.unknown().optional(),
        offset: core.serialization.number().optional(),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../..")).PaginatedResponse));

export declare namespace PositionInfo {
    interface Raw extends serializers.PaginatedResponse.Raw {
        data: serializers.PositionData.Raw[];
        next?: unknown | null;
        offset?: number | null;
    }
}
