/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const Relationships: core.serialization.Schema<serializers.Relationships.Raw, SayariAnalyticsApi.Relationships> =
    core.serialization.enum_([
        "judidical_representative_of",
        "has_judicial_representative",
        "legal_successor_of",
        "has_legal_successor",
        "family_of",
        "carrier_of",
        "has_carrier",
        "party_to",
        "has_party",
        "lawyer_of",
        "has_lawyer",
        "legal_representative_of",
        "has_legal_representative",
        "director_of",
        "has_director",
        "employee_of",
        "has_employee",
        "owner_of",
        "has_owner",
        "branch_of",
        "has_branch",
        "client_of",
        "has_client",
        "founder_of",
        "has_founder",
        "judicial_representative_of",
        "manager_of",
        "has_manager",
        "officer_of",
        "has_officer",
        "registered_agent_of",
        "has_registered_agent",
        "linked_to",
        "beneficial_owner_of",
        "has_beneficial_owner",
        "generic",
        "lawyer_in",
        "issuer_of",
        "has_issuer",
        "executive_of",
        "has_executive",
        "notify_party_of",
        "has_notify_party",
        "legal_predecessor_of",
        "has_legal_predecessor",
        "subsidiary_of",
        "has_subsidiary",
        "partner_of",
        "has_partner",
        "sole_proprietor_of",
        "has_sole_proprietor",
        "shipper_of",
        "shipped_by",
        "ships_to",
        "receives_from",
        "supervisor_of",
        "has_supervisor",
        "member_of_the_board_of",
        "has_member_of_the_board",
        "associate_of",
        "has_associate",
        "liquidator_of",
        "has_liquidator",
        "shareholder_of",
        "has_shareholder",
        "receiver_of",
        "received_by",
        "secretary_of",
        "has_secretary",
        "auditor_of",
        "has_auditor",
    ]);

export declare namespace Relationships {
    type Raw =
        | "judidical_representative_of"
        | "has_judicial_representative"
        | "legal_successor_of"
        | "has_legal_successor"
        | "family_of"
        | "carrier_of"
        | "has_carrier"
        | "party_to"
        | "has_party"
        | "lawyer_of"
        | "has_lawyer"
        | "legal_representative_of"
        | "has_legal_representative"
        | "director_of"
        | "has_director"
        | "employee_of"
        | "has_employee"
        | "owner_of"
        | "has_owner"
        | "branch_of"
        | "has_branch"
        | "client_of"
        | "has_client"
        | "founder_of"
        | "has_founder"
        | "judicial_representative_of"
        | "manager_of"
        | "has_manager"
        | "officer_of"
        | "has_officer"
        | "registered_agent_of"
        | "has_registered_agent"
        | "linked_to"
        | "beneficial_owner_of"
        | "has_beneficial_owner"
        | "generic"
        | "lawyer_in"
        | "issuer_of"
        | "has_issuer"
        | "executive_of"
        | "has_executive"
        | "notify_party_of"
        | "has_notify_party"
        | "legal_predecessor_of"
        | "has_legal_predecessor"
        | "subsidiary_of"
        | "has_subsidiary"
        | "partner_of"
        | "has_partner"
        | "sole_proprietor_of"
        | "has_sole_proprietor"
        | "shipper_of"
        | "shipped_by"
        | "ships_to"
        | "receives_from"
        | "supervisor_of"
        | "has_supervisor"
        | "member_of_the_board_of"
        | "has_member_of_the_board"
        | "associate_of"
        | "has_associate"
        | "liquidator_of"
        | "has_liquidator"
        | "shareholder_of"
        | "has_shareholder"
        | "receiver_of"
        | "received_by"
        | "secretary_of"
        | "has_secretary"
        | "auditor_of"
        | "has_auditor";
}
