/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const ReportingPeriodType: core.serialization.Schema<
    serializers.ReportingPeriodType.Raw,
    Sayari.ReportingPeriodType
> = core.serialization.enum_([
    "annual_fiscal",
    "last_twelve_months",
    "quarterly_fiscal",
    "semi_annual_fiscal",
    "year_to_date_fiscal",
]);

export declare namespace ReportingPeriodType {
    export type Raw =
        | "annual_fiscal"
        | "last_twelve_months"
        | "quarterly_fiscal"
        | "semi_annual_fiscal"
        | "year_to_date_fiscal";
}
