/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const RiskIntelligenceProperties: core.serialization.ObjectSchema<
    serializers.RiskIntelligenceProperties.Raw,
    SayariAnalyticsApi.RiskIntelligenceProperties
> = core.serialization.object({
    authority: core.serialization.string().optional(),
    list: core.serialization.string().optional(),
    program: core.serialization.string().optional(),
    reason: core.serialization.string().optional(),
    type: core.serialization.lazy(async () => (await import("../../..")).Tag),
});

export declare namespace RiskIntelligenceProperties {
    interface Raw {
        authority?: string | null;
        list?: string | null;
        program?: string | null;
        reason?: string | null;
        type: serializers.Tag.Raw;
    }
}
