/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const StatusContext: core.serialization.Schema<serializers.StatusContext.Raw, Sayari.StatusContext> =
    core.serialization.enum_([
        "broker_license",
        "general_partnership_status",
        "investment_advisor_license",
        "limited_liability_partnership_status",
        "sole_proprietorship_status",
    ]);

export declare namespace StatusContext {
    export type Raw =
        | "broker_license"
        | "general_partnership_status"
        | "investment_advisor_license"
        | "limited_liability_partnership_status"
        | "sole_proprietorship_status";
}
