/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const WeakIdentifierProperties: core.serialization.ObjectSchema<
    serializers.WeakIdentifierProperties.Raw,
    SayariAnalyticsApi.WeakIdentifierProperties
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("../../..")).WeakIdentifierType),
    value: core.serialization.string(),
});

export declare namespace WeakIdentifierProperties {
    interface Raw {
        type: serializers.WeakIdentifierType.Raw;
        value: string;
    }
}
