/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { SearchResults } from "./SearchResults";
import { PaginatedResponse } from "../../baseTypes/types/PaginatedResponse";

export const EntitySearchResponse: core.serialization.ObjectSchema<
    serializers.EntitySearchResponse.Raw,
    Sayari.EntitySearchResponse
> = core.serialization
    .object({
        offset: core.serialization.number(),
        next: core.serialization.boolean(),
        data: core.serialization.list(SearchResults),
    })
    .extend(PaginatedResponse);

export declare namespace EntitySearchResponse {
    interface Raw extends PaginatedResponse.Raw {
        offset: number;
        next: boolean;
        data: SearchResults.Raw[];
    }
}
