/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { OntologyLanguagesFilters } from "./OntologyLanguagesFilters";
import { OntologyLanguage } from "./OntologyLanguage";

export const GetOntologyLanguagesResponse: core.serialization.ObjectSchema<
    serializers.GetOntologyLanguagesResponse.Raw,
    Sayari.GetOntologyLanguagesResponse
> = core.serialization.object({
    filters: OntologyLanguagesFilters,
    data: core.serialization.list(OntologyLanguage),
    totalCount: core.serialization.property("total_count", core.serialization.number()),
});

export declare namespace GetOntologyLanguagesResponse {
    export interface Raw {
        filters: OntologyLanguagesFilters.Raw;
        data: OntologyLanguage.Raw[];
        total_count: number;
    }
}
