/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { OntologyCurrenciesFilters } from "./OntologyCurrenciesFilters";
import { OntologyCurrency } from "./OntologyCurrency";

export const GetOntologyCurrenciesResponse: core.serialization.ObjectSchema<
    serializers.GetOntologyCurrenciesResponse.Raw,
    Sayari.GetOntologyCurrenciesResponse
> = core.serialization.object({
    filters: OntologyCurrenciesFilters,
    data: core.serialization.list(OntologyCurrency),
    totalCount: core.serialization.property("total_count", core.serialization.number()),
});

export declare namespace GetOntologyCurrenciesResponse {
    export interface Raw {
        filters: OntologyCurrenciesFilters.Raw;
        data: OntologyCurrency.Raw[];
        total_count: number;
    }
}
