/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { Currency } from "../../generatedTypes/types/Currency";

export const OntologyCurrency: core.serialization.ObjectSchema<
    serializers.OntologyCurrency.Raw,
    Sayari.OntologyCurrency
> = core.serialization.object({
    id: Currency,
    label: core.serialization.string(),
});

export declare namespace OntologyCurrency {
    export interface Raw {
        id: Currency.Raw;
        label: string;
    }
}
