/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { Currency } from "../../generatedTypes/types/Currency";

export const OntologyCurrenciesFilters: core.serialization.ObjectSchema<
    serializers.OntologyCurrenciesFilters.Raw,
    Sayari.OntologyCurrenciesFilters
> = core.serialization.object({
    id: core.serialization.list(Currency).optional(),
});

export declare namespace OntologyCurrenciesFilters {
    export interface Raw {
        id?: Currency.Raw[] | null;
    }
}
