/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AdditionalInformationProperties {
    /** as-of date */
    date?: string;
    /** start date */
    fromDate?: string;
    /** end date */
    toDate?: string;
    /** The type of additional information being conveyed */
    type?: string;
    /** The additional information itself */
    value?: string;
}
