/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AdditionalInformationProperties {
    /** as-of date of attribute */
    date?: string;
    /** extra information of attribute */
    extra?: Record<string, unknown>;
    /** start date of attribute */
    fromDate?: string;
    /** end date of attribute */
    toDate?: string;
    /** The type of additional information being conveyed */
    type?: string;
    /** The additional information itself */
    value?: string;
}
