/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface AttributeDetails {
    additionalInformation?: Sayari.AdditionalInformationInfo;
    address?: Sayari.AddressInfo;
    businessPurpose?: Sayari.BusinessPurposeInfo;
    companyType?: Sayari.CompanyTypeInfo;
    contact?: Sayari.ContactInfo;
    country?: Sayari.CountryInfo;
    dateOfBirth?: Sayari.DateOfBirthInfo;
    finances?: Sayari.FinancesInfo;
    financials?: Sayari.FinancialsInfo;
    gender?: Sayari.GenderInfo;
    generic?: Sayari.GenericInfo;
    identifier?: Sayari.IdentifierInfo;
    measurement?: Sayari.MeasurementInfo;
    monetaryValue?: Sayari.MonetaryValueInfo;
    name?: Sayari.NameInfo;
    personStatus?: Sayari.PersonStatusInfo;
    position?: Sayari.PositionInfo;
    riskIntelligence?: Sayari.RiskIntelligenceInfo;
    shares?: Sayari.SharesInfo;
    status?: Sayari.StatusInfo;
    translatedName?: Sayari.TranslatedNameInfo;
    weakIdentifier?: Sayari.WeakIdentifierInfo;
}
