/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Attributes =
    | "address"
    | "shares"
    | "person_status"
    | "name"
    | "financials"
    | "risk_intelligence"
    | "gender"
    | "company_type"
    | "date_of_birth"
    | "measurement"
    | "generic"
    | "identifier"
    | "status"
    | "finances"
    | "weak_identifier"
    | "translated_name"
    | "contact"
    | "additional_information"
    | "position"
    | "monetary_value"
    | "country"
    | "business_purpose";

export const Attributes = {
    Address: "address",
    Shares: "shares",
    PersonStatus: "person_status",
    Name: "name",
    Financials: "financials",
    RiskIntelligence: "risk_intelligence",
    Gender: "gender",
    CompanyType: "company_type",
    DateOfBirth: "date_of_birth",
    Measurement: "measurement",
    Generic: "generic",
    Identifier: "identifier",
    Status: "status",
    Finances: "finances",
    WeakIdentifier: "weak_identifier",
    TranslatedName: "translated_name",
    Contact: "contact",
    AdditionalInformation: "additional_information",
    Position: "position",
    MonetaryValue: "monetary_value",
    Country: "country",
    BusinessPurpose: "business_purpose",
} as const;
