/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * Text and/or a code (NAICS, NACE, ISIC, etc.) that describes what a company is legally allowed to do or produce
 */
export interface BusinessPurposeInfo extends Sayari.PaginatedResponse {
    data: Sayari.BusinessPurposeData[];
    next?: unknown;
    offset?: number;
}
