/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * Contact information for an entity
 */
export interface ContactInfo extends Sayari.PaginatedResponse {
    data: Sayari.ContactData[];
    next?: unknown;
    offset?: number;
}
