/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Currency enums are normalized representations of currencies
 */
export type Currency =
    /**
     * Afghani/971/2 */
    | "AFN"
    /**
     * Euro/978/2 */
    | "EUR"
    /**
     * Lek/008/2 */
    | "ALL"
    /**
     * Algerian Dinar/012/2 */
    | "DZD"
    /**
     * US Dollar/840/2 */
    | "USD"
    /**
     * Kwanza/973/2 */
    | "AOA"
    /**
     * East Caribbean Dollar/951/2 */
    | "XCD"
    /**
     * Argentine Peso/032/2 */
    | "ARS"
    /**
     * Armenian Dram/051/2 */
    | "AMD"
    /**
     * Aruban Florin/533/2 */
    | "AWG"
    /**
     * Australian Dollar/036/2 */
    | "AUD"
    /**
     * Azerbaijan Manat/944/2 */
    | "AZN"
    /**
     * Bahamian Dollar/044/2 */
    | "BSD"
    /**
     * Bahraini Dinar/048/3 */
    | "BHD"
    /**
     * Taka/050/2 */
    | "BDT"
    /**
     * Barbados Dollar/052/2 */
    | "BBD"
    /**
     * Belarusian Ruble/933/2 */
    | "BYN"
    /**
     * Belize Dollar/084/2 */
    | "BZD"
    /**
     * CFA Franc BCEAO/952/0 */
    | "XOF"
    /**
     * Bermudian Dollar/060/2 */
    | "BMD"
    /**
     * Indian Rupee/356/2 */
    | "INR"
    /**
     * Ngultrum/064/2 */
    | "BTN"
    /**
     * Boliviano/068/2 */
    | "BOB"
    /**
     * Mvdol/984/2 */
    | "BOV"
    /**
     * Convertible Mark/977/2 */
    | "BAM"
    /**
     * Pula/072/2 */
    | "BWP"
    /**
     * Norwegian Krone/578/2 */
    | "NOK"
    /**
     * Brazilian Real/986/2 */
    | "BRL"
    /**
     * Brunei Dollar/096/2 */
    | "BND"
    /**
     * Bulgarian Lev/975/2 */
    | "BGN"
    /**
     * Burundi Franc/108/0 */
    | "BIF"
    /**
     * Cabo Verde Escudo/132/2 */
    | "CVE"
    /**
     * Riel/116/2 */
    | "KHR"
    /**
     * CFA Franc BEAC/950/0 */
    | "XAF"
    /**
     * Canadian Dollar/124/2 */
    | "CAD"
    /**
     * Cayman Islands Dollar/136/2 */
    | "KYD"
    /**
     * Chilean Peso/152/0 */
    | "CLP"
    /**
     * Unidad de Fomento/990/4 */
    | "CLF"
    /**
     * Yuan Renminbi/156/2 */
    | "CNY"
    /**
     * Colombian Peso/170/2 */
    | "COP"
    /**
     * Unidad de Valor Real/970/2 */
    | "COU"
    /**
     * Comorian Franc /174/0 */
    | "KMF"
    /**
     * Congolese Franc/976/2 */
    | "CDF"
    /**
     * New Zealand Dollar/554/2 */
    | "NZD"
    /**
     * Costa Rican Colon/188/2 */
    | "CRC"
    /**
     * Kuna/191/2 */
    | "HRK"
    /**
     * Cuban Peso/192/2 */
    | "CUP"
    /**
     * Peso Convertible/931/2 */
    | "CUC"
    /**
     * Netherlands Antillean Guilder/532/2 */
    | "ANG"
    /**
     * Czech Koruna/203/2 */
    | "CZK"
    /**
     * Danish Krone/208/2 */
    | "DKK"
    /**
     * Djibouti Franc/262/0 */
    | "DJF"
    /**
     * Dominican Peso/214/2 */
    | "DOP"
    /**
     * Egyptian Pound/818/2 */
    | "EGP"
    /**
     * El Salvador Colon/222/2 */
    | "SVC"
    /**
     * Nakfa/232/2 */
    | "ERN"
    /**
     * Ethiopian Birr/230/2 */
    | "ETB"
    /**
     * Falkland Islands Pound/238/2 */
    | "FKP"
    /**
     * Fiji Dollar/242/2 */
    | "FJD"
    /**
     * CFP Franc/953/0 */
    | "XPF"
    /**
     * Dalasi/270/2 */
    | "GMD"
    /**
     * Lari/981/2 */
    | "GEL"
    /**
     * Ghana Cedi/936/2 */
    | "GHS"
    /**
     * Gibraltar Pound/292/2 */
    | "GIP"
    /**
     * Quetzal/320/2 */
    | "GTQ"
    /**
     * Pound Sterling/826/2 */
    | "GBP"
    /**
     * Guinean Franc/324/0 */
    | "GNF"
    /**
     * Guyana Dollar/328/2 */
    | "GYD"
    /**
     * Gourde/332/2 */
    | "HTG"
    /**
     * Lempira/340/2 */
    | "HNL"
    /**
     * Hong Kong Dollar/344/2 */
    | "HKD"
    /**
     * Forint/348/2 */
    | "HUF"
    /**
     * Iceland Krona/352/0 */
    | "ISK"
    /**
     * Rupiah/360/2 */
    | "IDR"
    /**
     * SDR (Special Drawing Right)/960/N.A. */
    | "XDR"
    /**
     * Iranian Rial/364/2 */
    | "IRR"
    /**
     * Iraqi Dinar/368/3 */
    | "IQD"
    /**
     * New Israeli Sheqel/376/2 */
    | "ILS"
    /**
     * Jamaican Dollar/388/2 */
    | "JMD"
    /**
     * Yen/392/0 */
    | "JPY"
    /**
     * Jordanian Dinar/400/3 */
    | "JOD"
    /**
     * Tenge/398/2 */
    | "KZT"
    /**
     * Kenyan Shilling/404/2 */
    | "KES"
    /**
     * North Korean Won/408/2 */
    | "KPW"
    /**
     * Won/410/0 */
    | "KRW"
    /**
     * Kuwaiti Dinar/414/3 */
    | "KWD"
    /**
     * Som/417/2 */
    | "KGS"
    /**
     * Lao Kip/418/2 */
    | "LAK"
    /**
     * Lebanese Pound/422/2 */
    | "LBP"
    /**
     * Loti/426/2 */
    | "LSL"
    /**
     * Rand/710/2 */
    | "ZAR"
    /**
     * Liberian Dollar/430/2 */
    | "LRD"
    /**
     * Libyan Dinar/434/3 */
    | "LYD"
    /**
     * Swiss Franc/756/2 */
    | "CHF"
    /**
     * Pataca/446/2 */
    | "MOP"
    /**
     * Denar/807/2 */
    | "MKD"
    /**
     * Malagasy Ariary/969/2 */
    | "MGA"
    /**
     * Malawi Kwacha/454/2 */
    | "MWK"
    /**
     * Malaysian Ringgit/458/2 */
    | "MYR"
    /**
     * Rufiyaa/462/2 */
    | "MVR"
    /**
     * Ouguiya/929/2 */
    | "MRU"
    /**
     * Mauritius Rupee/480/2 */
    | "MUR"
    /**
     * ADB Unit of Account/965/N.A. */
    | "XUA"
    /**
     * Mexican Peso/484/2 */
    | "MXN"
    /**
     * Mexican Unidad de Inversion (UDI)/979/2 */
    | "MXV"
    /**
     * Moldovan Leu/498/2 */
    | "MDL"
    /**
     * Tugrik/496/2 */
    | "MNT"
    /**
     * Moroccan Dirham/504/2 */
    | "MAD"
    /**
     * Mozambique Metical/943/2 */
    | "MZN"
    /**
     * Kyat/104/2 */
    | "MMK"
    /**
     * Namibia Dollar/516/2 */
    | "NAD"
    /**
     * Nepalese Rupee/524/2 */
    | "NPR"
    /**
     * Cordoba Oro/558/2 */
    | "NIO"
    /**
     * Naira/566/2 */
    | "NGN"
    /**
     * Rial Omani/512/3 */
    | "OMR"
    /**
     * Pakistan Rupee/586/2 */
    | "PKR"
    /**
     * Balboa/590/2 */
    | "PAB"
    /**
     * Kina/598/2 */
    | "PGK"
    /**
     * Guarani/600/0 */
    | "PYG"
    /**
     * Sol/604/2 */
    | "PEN"
    /**
     * Philippine Peso/608/2 */
    | "PHP"
    /**
     * Zloty/985/2 */
    | "PLN"
    /**
     * Qatari Rial/634/2 */
    | "QAR"
    /**
     * Romanian Leu/946/2 */
    | "RON"
    /**
     * Russian Ruble/643/2 */
    | "RUB"
    /**
     * Rwanda Franc/646/0 */
    | "RWF"
    /**
     * Saint Helena Pound/654/2 */
    | "SHP"
    /**
     * Tala/882/2 */
    | "WST"
    /**
     * Dobra/930/2 */
    | "STN"
    /**
     * Saudi Riyal/682/2 */
    | "SAR"
    /**
     * Serbian Dinar/941/2 */
    | "RSD"
    /**
     * Seychelles Rupee/690/2 */
    | "SCR"
    /**
     * Leone/694/2 */
    | "SLL"
    /**
     * Singapore Dollar/702/2 */
    | "SGD"
    /**
     * Sucre/994/N.A. */
    | "XSU"
    /**
     * Solomon Islands Dollar/090/2 */
    | "SBD"
    /**
     * Somali Shilling/706/2 */
    | "SOS"
    /**
     * South Sudanese Pound/728/2 */
    | "SSP"
    /**
     * Sri Lanka Rupee/144/2 */
    | "LKR"
    /**
     * Sudanese Pound/938/2 */
    | "SDG"
    /**
     * Surinam Dollar/968/2 */
    | "SRD"
    /**
     * Lilangeni/748/2 */
    | "SZL"
    /**
     * Swedish Krona/752/2 */
    | "SEK"
    /**
     * WIR Euro/947/2 */
    | "CHE"
    /**
     * WIR Franc/948/2 */
    | "CHW"
    /**
     * Syrian Pound/760/2 */
    | "SYP"
    /**
     * New Taiwan Dollar/901/2 */
    | "TWD"
    /**
     * Somoni/972/2 */
    | "TJS"
    /**
     * Tanzanian Shilling/834/2 */
    | "TZS"
    /**
     * Baht/764/2 */
    | "THB"
    /**
     * Pa’anga/776/2 */
    | "TOP"
    /**
     * Trinidad and Tobago Dollar/780/2 */
    | "TTD"
    /**
     * Tunisian Dinar/788/3 */
    | "TND"
    /**
     * Turkish Lira/949/2 */
    | "TRY"
    /**
     * Turkmenistan New Manat/934/2 */
    | "TMT"
    /**
     * Uganda Shilling/800/0 */
    | "UGX"
    /**
     * Hryvnia/980/2 */
    | "UAH"
    /**
     * UAE Dirham/784/2 */
    | "AED"
    /**
     * US Dollar (Next day)/997/2 */
    | "USN"
    /**
     * Peso Uruguayo/858/2 */
    | "UYU"
    /**
     * Uruguay Peso en Unidades Indexadas (UI)/940/0 */
    | "UYI"
    /**
     * Unidad Previsional/927/4 */
    | "UYW"
    /**
     * Uzbekistan Sum/860/2 */
    | "UZS"
    /**
     * Vatu/548/0 */
    | "VUV"
    /**
     * Bolívar Soberano/928/2 */
    | "VES"
    /**
     * Dong/704/0 */
    | "VND"
    /**
     * Yemeni Rial/886/2 */
    | "YER"
    /**
     * Zambian Kwacha/967/2 */
    | "ZMW"
    /**
     * Zimbabwe Dollar/932/2 */
    | "ZWL"
    /**
     * Bond Markets Unit European Composite Unit (EURCO)/955/N.A. */
    | "XBA"
    /**
     * Bond Markets Unit European Monetary Unit (E.M.U.-6)/956/N.A. */
    | "XBB"
    /**
     * Bond Markets Unit European Unit of Account 9 (E.U.A.-9)/957/N.A. */
    | "XBC"
    /**
     * Bond Markets Unit European Unit of Account 17 (E.U.A.-17)/958/N.A. */
    | "XBD"
    /**
     * Codes specifically reserved for testing purposes/963/N.A. */
    | "XTS"
    /**
     * The codes assigned for transactions where no currency is involved/999/N.A. */
    | "XXX"
    /**
     * Gold/959/N.A. */
    | "XAU"
    /**
     * Palladium/964/N.A. */
    | "XPD"
    /**
     * Platinum/962/N.A. */
    | "XPT"
    /**
     * Silver/961/N.A. */
    | "XAG"
    /**
     * Latvian Lat; See https://en.wikipedia.org/wiki/Latvian_lats */
    | "LVL"
    /**
     * Slovak Koruna */
    | "SKK"
    /**
     * Italian Lira */
    | "ITL"
    /**
     * Dutch guilder */
    | "NLG"
    /**
     * Belgian franc */
    | "BEF"
    /**
     * Mauritanian Ouguiya */
    | "MRO"
    /**
     * Ukrainian Hryvnia */
    | "UKH";

export const Currency = {
    Afn: "AFN",
    Eur: "EUR",
    All: "ALL",
    Dzd: "DZD",
    Usd: "USD",
    Aoa: "AOA",
    Xcd: "XCD",
    Ars: "ARS",
    Amd: "AMD",
    Awg: "AWG",
    Aud: "AUD",
    Azn: "AZN",
    Bsd: "BSD",
    Bhd: "BHD",
    Bdt: "BDT",
    Bbd: "BBD",
    Byn: "BYN",
    Bzd: "BZD",
    Xof: "XOF",
    Bmd: "BMD",
    Inr: "INR",
    Btn: "BTN",
    Bob: "BOB",
    Bov: "BOV",
    Bam: "BAM",
    Bwp: "BWP",
    Nok: "NOK",
    Brl: "BRL",
    Bnd: "BND",
    Bgn: "BGN",
    Bif: "BIF",
    Cve: "CVE",
    Khr: "KHR",
    Xaf: "XAF",
    Cad: "CAD",
    Kyd: "KYD",
    Clp: "CLP",
    Clf: "CLF",
    Cny: "CNY",
    Cop: "COP",
    Cou: "COU",
    Kmf: "KMF",
    Cdf: "CDF",
    Nzd: "NZD",
    Crc: "CRC",
    Hrk: "HRK",
    Cup: "CUP",
    Cuc: "CUC",
    Ang: "ANG",
    Czk: "CZK",
    Dkk: "DKK",
    Djf: "DJF",
    Dop: "DOP",
    Egp: "EGP",
    Svc: "SVC",
    Ern: "ERN",
    Etb: "ETB",
    Fkp: "FKP",
    Fjd: "FJD",
    Xpf: "XPF",
    Gmd: "GMD",
    Gel: "GEL",
    Ghs: "GHS",
    Gip: "GIP",
    Gtq: "GTQ",
    Gbp: "GBP",
    Gnf: "GNF",
    Gyd: "GYD",
    Htg: "HTG",
    Hnl: "HNL",
    Hkd: "HKD",
    Huf: "HUF",
    Isk: "ISK",
    Idr: "IDR",
    Xdr: "XDR",
    Irr: "IRR",
    Iqd: "IQD",
    Ils: "ILS",
    Jmd: "JMD",
    Jpy: "JPY",
    Jod: "JOD",
    Kzt: "KZT",
    Kes: "KES",
    Kpw: "KPW",
    Krw: "KRW",
    Kwd: "KWD",
    Kgs: "KGS",
    Lak: "LAK",
    Lbp: "LBP",
    Lsl: "LSL",
    Zar: "ZAR",
    Lrd: "LRD",
    Lyd: "LYD",
    Chf: "CHF",
    Mop: "MOP",
    Mkd: "MKD",
    Mga: "MGA",
    Mwk: "MWK",
    Myr: "MYR",
    Mvr: "MVR",
    Mru: "MRU",
    Mur: "MUR",
    Xua: "XUA",
    Mxn: "MXN",
    Mxv: "MXV",
    Mdl: "MDL",
    Mnt: "MNT",
    Mad: "MAD",
    Mzn: "MZN",
    Mmk: "MMK",
    Nad: "NAD",
    Npr: "NPR",
    Nio: "NIO",
    Ngn: "NGN",
    Omr: "OMR",
    Pkr: "PKR",
    Pab: "PAB",
    Pgk: "PGK",
    Pyg: "PYG",
    Pen: "PEN",
    Php: "PHP",
    Pln: "PLN",
    Qar: "QAR",
    Ron: "RON",
    Rub: "RUB",
    Rwf: "RWF",
    Shp: "SHP",
    Wst: "WST",
    Stn: "STN",
    Sar: "SAR",
    Rsd: "RSD",
    Scr: "SCR",
    Sll: "SLL",
    Sgd: "SGD",
    Xsu: "XSU",
    Sbd: "SBD",
    Sos: "SOS",
    Ssp: "SSP",
    Lkr: "LKR",
    Sdg: "SDG",
    Srd: "SRD",
    Szl: "SZL",
    Sek: "SEK",
    Che: "CHE",
    Chw: "CHW",
    Syp: "SYP",
    Twd: "TWD",
    Tjs: "TJS",
    Tzs: "TZS",
    Thb: "THB",
    Top: "TOP",
    Ttd: "TTD",
    Tnd: "TND",
    Try: "TRY",
    Tmt: "TMT",
    Ugx: "UGX",
    Uah: "UAH",
    Aed: "AED",
    Usn: "USN",
    Uyu: "UYU",
    Uyi: "UYI",
    Uyw: "UYW",
    Uzs: "UZS",
    Vuv: "VUV",
    Ves: "VES",
    Vnd: "VND",
    Yer: "YER",
    Zmw: "ZMW",
    Zwl: "ZWL",
    Xba: "XBA",
    Xbb: "XBB",
    Xbc: "XBC",
    Xbd: "XBD",
    Xts: "XTS",
    Xxx: "XXX",
    Xau: "XAU",
    Xpd: "XPD",
    Xpt: "XPT",
    Xag: "XAG",
    Lvl: "LVL",
    Skk: "SKK",
    Itl: "ITL",
    Nlg: "NLG",
    Bef: "BEF",
    Mro: "MRO",
    Ukh: "UKH",
} as const;
