/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DateOfBirthProperties {
    /** as-of date */
    date?: string;
    /** start date */
    fromDate?: string;
    /** end date */
    toDate?: string;
    /** The date of birth in YYYY-MM-DD, YYYY-MM, or YYYY format */
    value: string;
}
