/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../../index";

/**
 * A summary of financial information at one point in time
 */
export interface FinancialsInfo extends SayariAnalyticsApi.PaginatedResponse {
    data: SayariAnalyticsApi.FinancialsData[];
    next?: unknown;
    offset?: number;
}
