/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GenericProperties {
    /** We would probably group by type in a GUI */
    type?: string;
    value?: string;
}
