/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

/**
 * A placeholder attribute. Rarely used. A generic attribute typically does not fit any other attribute type.
 */
export interface GenericInfo extends Sayari.PaginatedResponse {
    data: Sayari.GenericData[];
    next?: unknown;
    offset?: number;
}
