/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface IdentifierData extends Sayari.AttributeData {
    properties: Sayari.IdentifierProperties;
}
