/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface MeasurementProperties {
    /** as-of date */
    date?: string;
    /** start date */
    fromDate?: string;
    /** end date */
    toDate?: string;
    /** Type of the measurement */
    type: Sayari.MeasurementType;
    /** The unit of the measurement */
    unit: Sayari.Unit;
    /** The value of the measurement */
    value: number;
}
