/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface NameProperties {
    context?: string;
    /** as-of date of attribute */
    date?: string;
    /** extra information of attribute */
    extra?: Record<string, unknown>;
    /** start date of attribute */
    fromDate?: string;
    /** The language that the name is in */
    language?: Sayari.Language;
    /** end date of attribute */
    toDate?: string;
    /** The name value translated to English */
    translated?: string;
    /** The name value transliterated to English */
    transliterated?: string;
    /** The name, as text */
    value: string;
}
