/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Person status enums describe different life events
 */
export type PersonStatus = "born" | "died" | "married";

export const PersonStatus = {
    Born: "born",
    Died: "died",
    Married: "married",
} as const;
