/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as SayariAnalyticsApi from "../../..";

/**
 * A key event in a person's life, usually temporal
 */
export interface PersonStatusInfo extends SayariAnalyticsApi.PaginatedResponse {
    data: SayariAnalyticsApi.PersonStatusData[];
    next?: unknown;
    offset?: number;
}
