/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Reporting period type enums designate the type of statement period the values in a financials attribute are measured for.
 */
export type ReportingPeriodType =
    /**
     * Reported for the fiscal year */
    | "annual_fiscal"
    /**
     * Covers the preceding twelve months */
    | "last_twelve_months"
    /**
     * Reported quarterly in the fiscal year */
    | "quarterly_fiscal"
    /**
     * Reported twice a year in the fiscal year */
    | "semi_annual_fiscal"
    /**
     * Covers the year up until the reporting period */
    | "year_to_date_fiscal";
export const ReportingPeriodType = {
    AnnualFiscal: "annual_fiscal",
    LastTwelveMonths: "last_twelve_months",
    QuarterlyFiscal: "quarterly_fiscal",
    SemiAnnualFiscal: "semi_annual_fiscal",
    YearToDateFiscal: "year_to_date_fiscal",
} as const;
