/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface StatusProperties {
    /** The type of status, such as license or partnership type */
    context?: Sayari.StatusContext;
    /** as-of date */
    date?: string;
    /** start date */
    fromDate?: string;
    /** The raw status text */
    text?: string;
    /** end date */
    toDate?: string;
    /** The status, normalized to one of the status enums */
    value?: Sayari.CompanyStatus;
}
