/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as SayariAnalyticsApi from "../../../../index";
export interface GetToken {
    clientId: SayariAnalyticsApi.ClientId;
    clientSecret: SayariAnalyticsApi.ClientSecret;
    audience: SayariAnalyticsApi.Audience;
    grantType: SayariAnalyticsApi.GrantType;
}
