/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../index";

export interface ProjectEntitySupplyChainSnapshotDetailData {
    snapshotId: string;
    label: string;
    releaseTag: string;
    partialResults: boolean;
    exploredCount: number;
    createdAt: string;
    updatedAt: string;
    nodes: Sayari.SupplyChainNode[];
    edges: Sayari.SupplyChainEdge[];
}
