/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface SupplyChainNode {
    id: string;
    entityId: string;
    label: string;
    type: string;
    riskFactors: string[];
    countries: string[];
}
