/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const MatchQuality: core.serialization.Schema<serializers.MatchQuality.Raw, Sayari.MatchQuality> =
    core.serialization.enum_(["high", "medium", "low"]);

export declare namespace MatchQuality {
    export type Raw = "high" | "medium" | "low";
}
