/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";

export const MatchExplanation: core.serialization.ObjectSchema<
    serializers.MatchExplanation.Raw,
    SayariAnalyticsApi.MatchExplanation
> = core.serialization.object({
    matched: core.serialization.string().optional(),
    uploaded: core.serialization.string().optional(),
    nameCustomTfIdfScore: core.serialization.number().optional(),
    highQualityMatchName: core.serialization.boolean().optional(),
});

export declare namespace MatchExplanation {
    interface Raw {
        matched?: string | null;
        uploaded?: string | null;
        nameCustomTfIdfScore?: number | null;
        highQualityMatchName?: boolean | null;
    }
}
