/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const ProfileEnum: core.serialization.Schema<serializers.ProfileEnum.Raw, Sayari.ProfileEnum> =
    core.serialization.enum_(["corporate", "supplier"]);

export declare namespace ProfileEnum {
    type Raw = "corporate" | "supplier";
}
