/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const Article: core.serialization.ObjectSchema<serializers.Article.Raw, Sayari.Article> =
    core.serialization.object({
        published: core.serialization.string(),
        riskFlags: core.serialization.property("risk_flags", core.serialization.list(core.serialization.string())),
        searchTerm: core.serialization.property("search_term", core.serialization.unknown()),
        snippet: core.serialization.string(),
        source: core.serialization.string(),
        title: core.serialization.string(),
        url: core.serialization.string(),
    });

export declare namespace Article {
    export interface Raw {
        published: string;
        risk_flags: string[];
        search_term?: unknown;
        snippet: string;
        source: string;
        title: string;
        url: string;
    }
}
