/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Sayari from "../../../../index";

/**
 * @example
 *     {}
 */
export interface GetProjectRiskChangesRequest {
    /**
     * The maximum number of risk changes to return. Default is 100.
     */
    limit?: number;
    /**
     * Token to retrieve the next page of risk changes
     */
    next?: string;
    /**
     * Token to retrieve the previous page of risk changes
     */
    prev?: string;
    /**
     * Sort by timestamp in ascending or descending order. Default is desc.
     */
    sortDate?: Sayari.SortOrder;
    /**
     * Filter risk changes from the provided date
     */
    filterFrom?: string;
    /**
     * Filter risk changes up to the provided date
     */
    filterTo?: string;
    /**
     * Filter risk changes for the provided risk factors
     */
    filterRiskFactor?: string[];
    /**
     * Filter risk changes for risk factors from the provided risk categories
     */
    filterRiskCategory?: string[];
}
