/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { Location } from "./Location";

export const Address: core.serialization.ObjectSchema<serializers.Address.Raw, Sayari.Address> =
    core.serialization.object({
        value: core.serialization.string(),
        country: core.serialization.string().optional(),
        city: core.serialization.string().optional(),
        state: core.serialization.string().optional(),
        location: Location.optional(),
    });

export declare namespace Address {
    export interface Raw {
        value: string;
        country?: string | null;
        city?: string | null;
        state?: string | null;
        location?: Location.Raw | null;
    }
}
