/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const AttributeType: core.serialization.ObjectSchema<serializers.AttributeType.Raw, Sayari.AttributeType> =
    core.serialization.object({
        field: core.serialization.string(),
        matchResolution: core.serialization.property("match_resolution", core.serialization.boolean()),
    });

export declare namespace AttributeType {
    export interface Raw {
        field: string;
        match_resolution: boolean;
    }
}
