/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { GroupedAttributeValue } from "./GroupedAttributeValue";

export const GroupedAttribute: core.serialization.ObjectSchema<
    serializers.GroupedAttribute.Raw,
    Sayari.GroupedAttribute
> = core.serialization.object({
    field: core.serialization.string(),
    matchResolution: core.serialization.property("match_resolution", core.serialization.boolean()),
    values: core.serialization.list(GroupedAttributeValue),
});

export declare namespace GroupedAttribute {
    export interface Raw {
        field: string;
        match_resolution: boolean;
        values: GroupedAttributeValue.Raw[];
    }
}
