/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const MatchedAttributes: core.serialization.ObjectSchema<
    serializers.MatchedAttributes.Raw,
    Sayari.MatchedAttributes
> = core.serialization.object({
    name: core.serialization.list(core.serialization.string()).optional(),
    address: core.serialization.list(core.serialization.string()).optional(),
    contact: core.serialization.list(core.serialization.string()).optional(),
    country: core.serialization.list(core.serialization.string()).optional(),
    identifier: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace MatchedAttributes {
    export interface Raw {
        name?: string[] | null;
        address?: string[] | null;
        contact?: string[] | null;
        country?: string[] | null;
        identifier?: string[] | null;
    }
}
