/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { RiskChangeFilters } from "./RiskChangeFilters";
import { ProjectEntityRiskChangesResponseData } from "./ProjectEntityRiskChangesResponseData";

export const ProjectEntityRiskChangesResponse: core.serialization.ObjectSchema<
    serializers.ProjectEntityRiskChangesResponse.Raw,
    Sayari.ProjectEntityRiskChangesResponse
> = core.serialization.object({
    filters: RiskChangeFilters,
    next: core.serialization.string().optional(),
    prev: core.serialization.string().optional(),
    limit: core.serialization.number(),
    data: ProjectEntityRiskChangesResponseData,
});

export declare namespace ProjectEntityRiskChangesResponse {
    export interface Raw {
        filters: RiskChangeFilters.Raw;
        next?: string | null;
        prev?: string | null;
        limit: number;
        data: ProjectEntityRiskChangesResponseData.Raw;
    }
}
