/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { TradeTraversalFilters } from "../../supplyChain/types/TradeTraversalFilters";
import { ProjectEntitySupplyChainSummaryResponseData } from "./ProjectEntitySupplyChainSummaryResponseData";

export const ProjectEntitySupplyChainSummaryResponse: core.serialization.ObjectSchema<
    serializers.ProjectEntitySupplyChainSummaryResponse.Raw,
    Sayari.ProjectEntitySupplyChainSummaryResponse
> = core.serialization.object({
    filters: TradeTraversalFilters,
    data: ProjectEntitySupplyChainSummaryResponseData,
});

export declare namespace ProjectEntitySupplyChainSummaryResponse {
    export interface Raw {
        filters: TradeTraversalFilters.Raw;
        data: ProjectEntitySupplyChainSummaryResponseData.Raw;
    }
}
