/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";
import { ProjectEntityResponse } from "./ProjectEntityResponse";
import { QualifiedCount } from "../../baseTypes/types/QualifiedCount";

export const ProjectEntitiesResponse: core.serialization.ObjectSchema<
    serializers.ProjectEntitiesResponse.Raw,
    Sayari.ProjectEntitiesResponse
> = core.serialization.object({
    limit: core.serialization.number(),
    data: core.serialization.list(ProjectEntityResponse),
    size: QualifiedCount,
    nextToken: core.serialization.property("next_token", core.serialization.string().optional()),
    prevToken: core.serialization.property("prev_token", core.serialization.string().optional()),
});

export declare namespace ProjectEntitiesResponse {
    export interface Raw {
        limit: number;
        data: ProjectEntityResponse.Raw[];
        size: QualifiedCount.Raw;
        next_token?: string | null;
        prev_token?: string | null;
    }
}
