/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const RiskChangeFactorChangeType: core.serialization.Schema<
    serializers.RiskChangeFactorChangeType.Raw,
    Sayari.RiskChangeFactorChangeType
> = core.serialization.enum_(["added", "removed"]);

export declare namespace RiskChangeFactorChangeType {
    export type Raw = "added" | "removed";
}
