/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const ShareInformation: core.serialization.ObjectSchema<
    serializers.ShareInformation.Raw,
    Sayari.ShareInformation
> = core.serialization.object({
    percentage: core.serialization.number().optional(),
    numShares: core.serialization.property("num_shares", core.serialization.number().optional()),
    monetaryValue: core.serialization.property("monetary_value", core.serialization.number().optional()),
});

export declare namespace ShareInformation {
    export interface Raw {
        percentage?: number | null;
        num_shares?: number | null;
        monetary_value?: number | null;
    }
}
