/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as Sayari from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateProjectEntityTagsBody: core.serialization.ObjectSchema<
    serializers.UpdateProjectEntityTagsBody.Raw,
    Sayari.UpdateProjectEntityTagsBody
> = core.serialization.object({
    ids: core.serialization.list(core.serialization.string()),
});

export declare namespace UpdateProjectEntityTagsBody {
    export interface Raw {
        ids: string[];
    }
}
