name: ci

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every midnight (00:00 UTC)

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Compile
        run: yarn && yarn build
      - name: Notify Slack - Compile
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI Job *Compile* completed on `${{ github.ref }}` branch with status `${{ job.status }}`"}' https://hooks.slack.com/services/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

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Compile & Test
        run: yarn && yarn test
      - name: Notify Slack - Test
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI Job *Test* completed on `${{ github.ref }}` branch with status `${{ job.status }}`"}' https://hooks.slack.com/services/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

  run-examples:
    name: Run examples (to look for regressions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Build
        run: yarn && yarn build
      - name: Test examples
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running hello world"
          node examples/hello-world.mjs
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running smoke test"
          node examples/smoke-test.mjs
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running trade search"
          node examples/trade-search.mjs
      - name: Notify Slack - Run Examples
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI Job *Run Examples* completed on `${{ github.ref }}` branch with status `${{ job.status }}`"}' https://hooks.slack.com/services/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

  publish:
    needs: [ compile, test, run-examples ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.SDK_NPM_TOKEN }}
      - name: Notify Slack - Publish
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"CI Job *Publish* completed on `${{ github.ref }}` branch with status `${{ job.status }}`"}' https://hooks.slack.com/services/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
