name: ci

env:
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

permissions:
  contents: read       # Allows read access to the code in the repository

on:
  push:
  schedule:
    - cron: '0 0 * * *' # Runs every midnight (00:00 UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Compile
        run: yarn && yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Compile & Test
        run: yarn && yarn test

  run-examples:
    name: Run examples (to look for regressions)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Build
        run: yarn && yarn build
      - name: Test examples
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running hello world"
          node examples/hello-world.mjs
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running smoke test"
          node examples/smoke-test.mjs
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Running trade search"
          node examples/trade-search.mjs

  publish:
    needs: [ compile, test, run-examples ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.SDK_NPM_TOKEN }}

  notify-slack:
    name: Notify Slack
    needs: [compile, test, run-examples, publish]
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Send Slack Notification
        env:
          WEBHOOK_URL: ${{ secrets.GH_ACTION_WEBHOOK_URL }}
          GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          COMMIT_AUTHOR=$(echo "${{ github.event.head_commit.author.name }}")
          BRANCH=${{ github.ref_name }}

          if [ "${{ github.event_name }}" == "schedule" ]; then
            MESSAGE="CI-Nightly-Build completed successfully. See details here: $GITHUB_RUN_URL"
          else
            MESSAGE="CI Build for branch *${BRANCH}* by *${COMMIT_AUTHOR}* completed successfully. See details here: $GITHUB_RUN_URL"
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" $WEBHOOK_URL
