/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const EntityRelationshipCount: core.serialization.Schema<serializers.EntityRelationshipCount.Raw, SayariAnalyticsApi.EntityRelationshipCount>;
export declare namespace EntityRelationshipCount {
    type Raw = Record<serializers.Relationships.Raw, number | null | undefined>;
}
