/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const EntityDetails: core.serialization.ObjectSchema<serializers.EntityDetails.Raw, SayariAnalyticsApi.EntityDetails>;
export declare namespace EntityDetails {
    interface Raw extends serializers.EmbeddedEntity.Raw {
        registration_date?: serializers.EntityRegistrationDate.Raw | null;
        translated_label?: serializers.EntityTranslatedLabel.Raw | null;
        hs_code?: serializers.EntityHsCode.Raw | null;
        shipment_arrival?: serializers.ShipmentArrival.Raw | null;
        shipment_departure?: serializers.ShipmentDepartue.Raw | null;
        company_type?: serializers.CompanyType.Raw | null;
        latest_status?: serializers.Status.Raw | null;
        risk: serializers.EntityRisk.Raw;
        attributes?: serializers.AttributeDetails.Raw | null;
        relationships?: serializers.EntityRelationships.Raw | null;
        possibly_same_as?: serializers.PossiblySameAs.Raw | null;
        referenced_by?: serializers.ReferencedBy.Raw | null;
        matches?: serializers.EntityMatches.Raw | null;
    }
}
