/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
export const Identifier = core.serialization.object({
    value: core.serialization.string(),
    type: core.serialization.string(),
    label: core.serialization.string(),
});
