/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const PsaEntity: core.serialization.ObjectSchema<serializers.PsaEntity.Raw, SayariAnalyticsApi.PsaEntity>;
export declare namespace PsaEntity {
    interface Raw extends serializers.EmbeddedEntity.Raw {
        risk: serializers.EntityRisk.Raw;
    }
}
