/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../index";
import * as SayariAnalyticsApi from "../../../../api";
import * as core from "../../../../core";
export declare const SourceId: core.serialization.Schema<serializers.SourceId.Raw, SayariAnalyticsApi.SourceId>;
export declare namespace SourceId {
    type Raw = string;
}
